// IKEA soft-ice vlog - After Effects builder (generated by ikea_ae_build.py)
// Run in After Effects: File > Scripts > Run Script File...
(function () {
var DATA = {
 "duration": 42.233,
 "telops": [
  {
   "name": "00.10 \u65e5\u672c\u306f50\u5186",
   "t0": 0.1,
   "t1": 2.1,
   "lines": [
    {
     "size": 120,
     "runs": [
      {
       "text": "\u65e5\u672c\u306f",
       "accent": false,
       "k0": 0,
       "n": 3
      },
      {
       "text": "50\u5186",
       "accent": true,
       "k0": 3,
       "n": 3,
       "counter": [
        [
         0.1,
         "07\u5186"
        ],
        [
         0.1667,
         "27\u5186"
        ],
        [
         0.2333,
         "86\u5186"
        ],
        [
         0.3,
         "89\u5186"
        ],
        [
         0.3667,
         "73\u5186"
        ],
        [
         0.4333,
         "00\u5186"
        ],
        [
         0.55,
         "50\u5186"
        ]
       ]
      }
     ],
     "keys": {
      "dy": [
       [
        0.1,
        138.0,
        "fast"
       ],
       [
        0.52,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.1,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     2.1,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     0.1,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.1,
     [
      540,
      660
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.32
  },
  {
   "name": "00.55 \u672c\u5834\u306f\u3044\u304f\u3089\uff1f",
   "t0": 0.55,
   "t1": 2.1,
   "lines": [
    {
     "size": 114,
     "runs": [
      {
       "text": "\u672c\u5834\u306f",
       "accent": false,
       "k0": 0,
       "n": 3
      },
      {
       "text": "\u3044\u304f\u3089\uff1f",
       "accent": true,
       "k0": 3,
       "n": 4
      }
     ],
     "keys": {}
    }
   ],
   "anim": "cascade",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.55,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     2.1,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     0.55,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.55,
     [
      540,
      830
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     0.73,
     0,
     "fast"
    ],
    [
     1.13,
     100,
     "lin"
    ]
   ],
   "blur": null,
   "motionBlur": true,
   "chStagger": 0.06,
   "chDur": 0.32
  },
  {
   "name": "02.38 \u65e5\u672c\u3060\u3068",
   "t0": 2.38,
   "t1": 2.84,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u65e5\u672c\u3060\u3068",
       "accent": false,
       "k0": 0,
       "n": 4
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     2.38,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     2.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     2.38,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     2.38,
     0,
     "lin"
    ],
    [
     2.4466666666666668,
     100,
     "lin"
    ],
    [
     2.773333333333333,
     100,
     "lin"
    ],
    [
     2.84,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.03833333333333333,
   "chDur": 0.11499999999999999
  },
  {
   "name": "02.84 \u30a4\u30b1\u30a2\u306e",
   "t0": 2.84,
   "t1": 3.16,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a4\u30b1\u30a2\u306e",
       "accent": false,
       "k0": 0,
       "n": 4
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     2.84,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     2.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     2.84,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     2.84,
     0,
     "lin"
    ],
    [
     2.9066666666666667,
     100,
     "lin"
    ],
    [
     3.0933333333333333,
     100,
     "lin"
    ],
    [
     3.16,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.02666666666666669,
   "chDur": 0.08000000000000007
  },
  {
   "name": "03.16 \u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
   "t0": 3.16,
   "t1": 3.7,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
       "accent": false,
       "k0": 0,
       "n": 9
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     3.16,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     3.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     3.16,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     3.16,
     0,
     "lin"
    ],
    [
     3.226666666666667,
     100,
     "lin"
    ],
    [
     3.6333333333333333,
     100,
     "lin"
    ],
    [
     3.7,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.016875,
   "chDur": 0.135
  },
  {
   "name": "03.70 1\u500b50\u5186",
   "t0": 3.7,
   "t1": 4.38,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false,
       "k0": 0,
       "n": 2
      },
      {
       "text": "50\u5186",
       "accent": true,
       "k0": 2,
       "n": 3,
       "counter": [
        [
         3.7,
         "00\u5186"
        ],
        [
         3.7667,
         "80\u5186"
        ],
        [
         3.8333,
         "58\u5186"
        ],
        [
         3.9,
         "62\u5186"
        ],
        [
         3.9667,
         "06\u5186"
        ],
        [
         4.0333,
         "19\u5186"
        ],
        [
         4.15,
         "50\u5186"
        ]
       ]
      }
     ],
     "keys": {}
    }
   ],
   "anim": "pop",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     3.7,
     [
      55,
      55
     ],
     "fast"
    ],
    [
     3.8200000000000003,
     [
      110,
      110
     ],
     "io"
    ],
    [
     3.9200000000000004,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     4.38,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     3.7,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     3.7,
     [
      540,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     3.7,
     0,
     "lin"
    ],
    [
     3.766666666666667,
     100,
     "lin"
    ],
    [
     4.26,
     100,
     "io"
    ],
    [
     4.38,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.04249999999999998,
   "chDur": 0.16999999999999993
  },
  {
   "name": "04.38 \u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
   "t0": 4.38,
   "t1": 5.2,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
       "accent": false,
       "k0": 0,
       "n": 9
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     4.38,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     4.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     4.38,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     4.38,
     0,
     "lin"
    ],
    [
     4.446666666666666,
     100,
     "lin"
    ],
    [
     5.133333333333334,
     100,
     "lin"
    ],
    [
     5.2,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.02562500000000001,
   "chDur": 0.20500000000000007
  },
  {
   "name": "05.66 \u5b9f\u969b",
   "t0": 5.66,
   "t1": 6.02,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b9f\u969b",
       "accent": false,
       "k0": 0,
       "n": 2
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     5.66,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     5.66,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     5.66,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     5.66,
     0,
     "lin"
    ],
    [
     5.726666666666667,
     100,
     "lin"
    ],
    [
     5.953333333333333,
     100,
     "lin"
    ],
    [
     6.02,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.08999999999999986
  },
  {
   "name": "06.02 \u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
   "t0": 6.02,
   "t1": 7.22,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
       "accent": false,
       "k0": 0,
       "n": 7
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     6.02,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     6.02,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     6.02,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     6.02,
     0,
     "lin"
    ],
    [
     6.086666666666666,
     100,
     "lin"
    ],
    [
     7.153333333333333,
     100,
     "lin"
    ],
    [
     7.22,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.05000000000000001,
   "chDur": 0.30000000000000004
  },
  {
   "name": "07.75 \u8cb7\u3048\u308b\u306e\u304b\u3092",
   "t0": 7.75,
   "t1": 8.04,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8cb7\u3048\u308b\u306e\u304b\u3092",
       "accent": false,
       "k0": 0,
       "n": 6
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     7.75,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     7.75,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     7.75,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     7.75,
     0,
     "lin"
    ],
    [
     7.816666666666666,
     100,
     "lin"
    ],
    [
     7.973333333333333,
     100,
     "lin"
    ],
    [
     8.04,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.014499999999999957,
   "chDur": 0.07249999999999979
  },
  {
   "name": "08.04 \u898b\u3066\u307f\u307e\u3059",
   "t0": 8.04,
   "t1": 8.8,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u898b\u3066\u307f\u307e\u3059",
       "accent": false,
       "k0": 0,
       "n": 5
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     8.04,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     8.04,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     8.04,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     8.04,
     0,
     "lin"
    ],
    [
     8.106666666666666,
     100,
     "lin"
    ],
    [
     8.733333333333334,
     100,
     "lin"
    ],
    [
     8.8,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.0475000000000001,
   "chDur": 0.1900000000000004
  },
  {
   "name": "08.98 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 8.98,
   "t1": 10.22,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false,
       "k0": 0,
       "n": 7
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     8.98,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     8.98,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     8.98,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     8.98,
     0,
     "lin"
    ],
    [
     9.046666666666667,
     100,
     "lin"
    ],
    [
     10.153333333333334,
     100,
     "lin"
    ],
    [
     10.22,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.05166666666666667,
   "chDur": 0.31000000000000005
  },
  {
   "name": "10.22 9\u306a\u3093\u3067",
   "t0": 10.22,
   "t1": 11.74,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "9",
       "accent": true,
       "k0": 0,
       "n": 1
      },
      {
       "text": "\u306a\u3093\u3067",
       "accent": false,
       "k0": 1,
       "n": 3
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     10.22,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     10.22,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     10.22,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     10.22,
     0,
     "lin"
    ],
    [
     10.286666666666667,
     100,
     "lin"
    ],
    [
     11.673333333333334,
     100,
     "lin"
    ],
    [
     11.74,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.32
  },
  {
   "name": "11.74 150\u5186",
   "t0": 11.74,
   "t1": 12.96,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "150\u5186",
       "accent": true,
       "k0": 0,
       "n": 4,
       "counter": [
        [
         11.74,
         "425\u5186"
        ],
        [
         11.8067,
         "088\u5186"
        ],
        [
         11.8733,
         "959\u5186"
        ],
        [
         11.94,
         "940\u5186"
        ],
        [
         12.0067,
         "528\u5186"
        ],
        [
         12.0733,
         "616\u5186"
        ],
        [
         12.19,
         "150\u5186"
        ]
       ]
      }
     ],
     "keys": {}
    }
   ],
   "anim": "slide",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     11.74,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     12.96,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     11.74,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     11.74,
     [
      1240,
      950
     ],
     "fast"
    ],
    [
     12.06,
     [
      540,
      950
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     11.74,
     0,
     "lin"
    ],
    [
     11.806666666666667,
     100,
     "lin"
    ],
    [
     12.840000000000002,
     100,
     "io"
    ],
    [
     12.96,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     11.92,
     0,
     "fast"
    ],
    [
     12.32,
     100,
     "lin"
    ]
   ],
   "blur": null,
   "motionBlur": true,
   "chStagger": 0.06,
   "chDur": 0.30500000000000016
  },
  {
   "name": "12.10 \u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
   "t0": 12.1,
   "t1": 12.96,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
       "accent": false,
       "k0": 0,
       "n": 8
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     12.1,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     12.1,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     12.1,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     12.1,
     0,
     "lin"
    ],
    [
     12.166666666666666,
     100,
     "lin"
    ],
    [
     12.893333333333334,
     100,
     "lin"
    ],
    [
     12.96,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.030714285714285756,
   "chDur": 0.2150000000000003
  },
  {
   "name": "12.96 \u3053\u308c\u666e\u901a\u306b",
   "t0": 12.96,
   "t1": 13.74,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c\u666e\u901a\u306b",
       "accent": false,
       "k0": 0,
       "n": 5
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     12.96,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     12.96,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     12.96,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     12.96,
     0,
     "lin"
    ],
    [
     13.026666666666667,
     100,
     "lin"
    ],
    [
     13.673333333333334,
     100,
     "lin"
    ],
    [
     13.74,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.04874999999999996,
   "chDur": 0.19499999999999984
  },
  {
   "name": "14.38 \u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
   "t0": 14.38,
   "t1": 15.54,
   "lines": [
    {
     "size": 80,
     "runs": [
      {
       "text": "\u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
       "accent": false,
       "k0": 0,
       "n": 10
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     14.38,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     14.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     14.38,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     14.38,
     0,
     "lin"
    ],
    [
     14.446666666666667,
     100,
     "lin"
    ],
    [
     15.473333333333333,
     100,
     "lin"
    ],
    [
     15.54,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.03222222222222218,
   "chDur": 0.2899999999999996
  },
  {
   "name": "15.54 1\u500b112\u5186",
   "t0": 15.54,
   "t1": 16.72,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false,
       "k0": 0,
       "n": 2
      },
      {
       "text": "112\u5186",
       "accent": true,
       "k0": 2,
       "n": 4,
       "counter": [
        [
         15.54,
         "167\u5186"
        ],
        [
         15.6067,
         "381\u5186"
        ],
        [
         15.6733,
         "770\u5186"
        ],
        [
         15.74,
         "673\u5186"
        ],
        [
         15.8067,
         "510\u5186"
        ],
        [
         15.8733,
         "846\u5186"
        ],
        [
         15.99,
         "112\u5186"
        ]
       ]
      }
     ],
     "keys": {
      "dy": [
       [
        15.54,
        218.49999999999997,
        "fast"
       ],
       [
        15.959999999999999,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     15.54,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     16.72,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     15.54,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     15.54,
     [
      540,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     16.599999999999998,
     100,
     "io"
    ],
    [
     16.72,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     15.719999999999999,
     0,
     "fast"
    ],
    [
     16.119999999999997,
     100,
     "lin"
    ]
   ],
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.05899999999999998,
   "chDur": 0.29499999999999993
  },
  {
   "name": "16.72 \u3067\u8cb7\u3048\u307e\u3059\u306d",
   "t0": 16.72,
   "t1": 17.5,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3067\u8cb7\u3048\u307e\u3059\u306d",
       "accent": false,
       "k0": 0,
       "n": 6
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     16.72,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     16.72,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     16.72,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     16.72,
     0,
     "lin"
    ],
    [
     16.786666666666665,
     100,
     "lin"
    ],
    [
     17.433333333333334,
     100,
     "lin"
    ],
    [
     17.5,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.039000000000000055,
   "chDur": 0.19500000000000028
  },
  {
   "name": "17.76 \u30bb\u30c3\u30c8\u3057\u3066",
   "t0": 17.76,
   "t1": 18.8,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bb\u30c3\u30c8\u3057\u3066",
       "accent": false,
       "k0": 0,
       "n": 5
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     17.76,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     17.76,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     17.76,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     17.76,
     0,
     "lin"
    ],
    [
     17.826666666666668,
     100,
     "lin"
    ],
    [
     18.733333333333334,
     100,
     "lin"
    ],
    [
     18.8,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.2599999999999998
  },
  {
   "name": "19.16 \u3042\u3068\u306f\u3053\u3053\u3092",
   "t0": 19.16,
   "t1": 20.08,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u3068\u306f\u3053\u3053\u3092",
       "accent": false,
       "k0": 0,
       "n": 6
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     19.16,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     19.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     19.16,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     19.16,
     0,
     "lin"
    ],
    [
     19.226666666666667,
     100,
     "lin"
    ],
    [
     20.013333333333332,
     100,
     "lin"
    ],
    [
     20.08,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.04599999999999991,
   "chDur": 0.22999999999999954
  },
  {
   "name": "20.08 \u62bc\u3059\u3060\u3051\u3067\u3059\u306d",
   "t0": 20.08,
   "t1": 21.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u62bc\u3059\u3060\u3051",
       "accent": true,
       "k0": 0,
       "n": 4
      },
      {
       "text": "\u3067\u3059\u306d",
       "accent": false,
       "k0": 4,
       "n": 3
      }
     ],
     "keys": {}
    }
   ],
   "anim": "squash",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     20.08,
     [
      100,
      100
     ],
     "io"
    ],
    [
     20.159999999999997,
     [
      118,
      76
     ],
     "io"
    ],
    [
     20.259999999999998,
     [
      94,
      108
     ],
     "io"
    ],
    [
     20.36,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     20.08,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     20.08,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     20.88,
     100,
     "io"
    ],
    [
     21.0,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.03833333333333341,
   "chDur": 0.23000000000000043
  },
  {
   "name": "23.04 \u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
   "t0": 23.04,
   "t1": 24.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
       "accent": false,
       "k0": 0,
       "n": 9
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     23.04,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     23.04,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     23.04,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     23.04,
     0,
     "lin"
    ],
    [
     23.106666666666666,
     100,
     "lin"
    ],
    [
     23.933333333333334,
     100,
     "lin"
    ],
    [
     24.0,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.030000000000000027,
   "chDur": 0.2400000000000002
  },
  {
   "name": "24.84 \u5b9f\u969b\u306b\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 24.84,
   "t1": 26.04,
   "lines": [
    {
     "size": 80,
     "runs": [
      {
       "text": "\u5b9f\u969b\u306b\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false,
       "k0": 0,
       "n": 10
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     24.84,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     24.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     24.84,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     24.84,
     0,
     "lin"
    ],
    [
     24.906666666666666,
     100,
     "lin"
    ],
    [
     25.973333333333333,
     100,
     "lin"
    ],
    [
     26.04,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.03333333333333331,
   "chDur": 0.2999999999999998
  },
  {
   "name": "29.48 \u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
   "t0": 29.48,
   "t1": 30.48,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
       "accent": false,
       "k0": 0,
       "n": 7
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     29.48,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     29.48,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     29.48,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     29.48,
     0,
     "lin"
    ],
    [
     29.546666666666667,
     100,
     "lin"
    ],
    [
     30.413333333333334,
     100,
     "lin"
    ],
    [
     30.48,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.041666666666666664,
   "chDur": 0.25
  },
  {
   "name": "30.48 \u77ac\u9593\u306b",
   "t0": 30.48,
   "t1": 31.3,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u77ac\u9593\u306b",
       "accent": false,
       "k0": 0,
       "n": 3
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     30.48,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     30.48,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     30.48,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     30.48,
     0,
     "lin"
    ],
    [
     30.546666666666667,
     100,
     "lin"
    ],
    [
     31.233333333333334,
     100,
     "lin"
    ],
    [
     31.3,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.20500000000000007
  },
  {
   "name": "31.90 \u3046\u308f\u3063\uff01\u3063\u3066",
   "t0": 31.9,
   "t1": 32.78,
   "lines": [
    {
     "size": 134,
     "runs": [
      {
       "text": "\u3046\u308f\u3063\uff01",
       "accent": true,
       "k0": 0,
       "n": 4
      },
      {
       "text": "\u3063\u3066",
       "accent": false,
       "k0": 4,
       "n": 2
      }
     ],
     "keys": {}
    }
   ],
   "anim": "burst",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     31.9,
     [
      175,
      175
     ],
     "fast"
    ],
    [
     32.04,
     [
      94,
      94
     ],
     "io"
    ],
    [
     32.14,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     32.78,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     32.04,
     0.0,
     "io"
    ],
    [
     32.08,
     -7.0,
     "io"
    ],
    [
     32.12,
     6.0,
     "io"
    ],
    [
     32.16,
     -4.0,
     "io"
    ],
    [
     32.199999999999996,
     2.0,
     "io"
    ],
    [
     32.24,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     31.9,
     [
      540,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     31.9,
     0,
     "lin"
    ],
    [
     31.966666666666665,
     100,
     "lin"
    ],
    [
     32.660000000000004,
     100,
     "io"
    ],
    [
     32.78,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": true,
   "chStagger": 0.04400000000000013,
   "chDur": 0.22000000000000064
  },
  {
   "name": "32.78 \u8272\u3005\u3046\u307e\u3044",
   "t0": 32.78,
   "t1": 33.68,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8272\u3005\u3046\u307e\u3044",
       "accent": false,
       "k0": 0,
       "n": 5
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     32.78,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     32.78,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     32.78,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     32.78,
     0,
     "lin"
    ],
    [
     32.84666666666667,
     100,
     "lin"
    ],
    [
     33.61333333333333,
     100,
     "lin"
    ],
    [
     33.68,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.05624999999999991,
   "chDur": 0.22499999999999964
  },
  {
   "name": "33.68 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 33.68,
   "t1": 34.16,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false,
       "k0": 0,
       "n": 7
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     33.68,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     33.68,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     33.68,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     33.68,
     0,
     "lin"
    ],
    [
     33.74666666666667,
     100,
     "lin"
    ],
    [
     34.09333333333333,
     100,
     "lin"
    ],
    [
     34.16,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.01999999999999987,
   "chDur": 0.11999999999999922
  },
  {
   "name": "34.16 \u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
   "t0": 34.16,
   "t1": 35.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
       "accent": false,
       "k0": 0,
       "n": 9
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     34.16,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     34.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     34.16,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     34.16,
     0,
     "lin"
    ],
    [
     34.22666666666667,
     100,
     "lin"
    ],
    [
     34.93333333333333,
     100,
     "lin"
    ],
    [
     35.0,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.026250000000000107,
   "chDur": 0.21000000000000085
  },
  {
   "name": "35.14 \u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
   "t0": 35.14,
   "t1": 36.18,
   "lines": [
    {
     "size": 80,
     "runs": [
      {
       "text": "\u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
       "accent": false,
       "k0": 0,
       "n": 10
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     35.14,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     35.14,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     35.14,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     35.14,
     0,
     "lin"
    ],
    [
     35.20666666666667,
     100,
     "lin"
    ],
    [
     36.11333333333333,
     100,
     "lin"
    ],
    [
     36.18,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.028888888888888867,
   "chDur": 0.2599999999999998
  },
  {
   "name": "36.18 5\u500d\u6fc3\u7e2e",
   "t0": 36.18,
   "t1": 37.4,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "5\u500d\u6fc3\u7e2e",
       "accent": true,
       "k0": 0,
       "n": 4
      }
     ],
     "keys": {}
    }
   ],
   "anim": "cascade",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": true,
   "scale": [
    [
     36.18,
     [
      100,
      100
     ],
     "lin"
    ],
    [
     37.4,
     [
      103.0,
      103.0
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     36.18,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     36.18,
     [
      540,
      400
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     37.28,
     100,
     "io"
    ],
    [
     37.4,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": true,
   "chStagger": 0.06,
   "chDur": 0.3049999999999997
  },
  {
   "name": "36.84 \u3057\u305f\u307f\u305f\u3044\u306a",
   "t0": 36.84,
   "t1": 37.28,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3057\u305f\u307f\u305f\u3044\u306a",
       "accent": false,
       "k0": 0,
       "n": 6
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     36.84,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     36.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     36.84,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     36.84,
     0,
     "lin"
    ],
    [
     36.90666666666667,
     100,
     "lin"
    ],
    [
     37.21333333333333,
     100,
     "lin"
    ],
    [
     37.28,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.021999999999999888,
   "chDur": 0.10999999999999943
  },
  {
   "name": "37.28 \u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
   "t0": 37.28,
   "t1": 38.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
       "accent": false,
       "k0": 0,
       "n": 8
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     37.28,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     37.28,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     37.28,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     37.28,
     0,
     "lin"
    ],
    [
     37.34666666666667,
     100,
     "lin"
    ],
    [
     37.93333333333333,
     100,
     "lin"
    ],
    [
     38.0,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.025714285714285672,
   "chDur": 0.17999999999999972
  },
  {
   "name": "38.00 \u3053\u308c",
   "t0": 38.0,
   "t1": 38.6,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c",
       "accent": false,
       "k0": 0,
       "n": 2
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     38.0,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     38.0,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     38.0,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     38.0,
     0,
     "lin"
    ],
    [
     38.06666666666667,
     100,
     "lin"
    ],
    [
     38.53333333333333,
     100,
     "lin"
    ],
    [
     38.6,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.15000000000000036
  },
  {
   "name": "39.24 \u610f\u5916\u3068\u306d",
   "t0": 39.24,
   "t1": 39.68,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u610f\u5916\u3068\u306d",
       "accent": false,
       "k0": 0,
       "n": 4
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     39.24,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     39.24,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     39.24,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     39.24,
     0,
     "lin"
    ],
    [
     39.30666666666667,
     100,
     "lin"
    ],
    [
     39.61333333333333,
     100,
     "lin"
    ],
    [
     39.68,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.03666666666666648,
   "chDur": 0.10999999999999943
  },
  {
   "name": "40.30 \u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
   "t0": 40.3,
   "t1": 42.3,
   "lines": [
    {
     "size": 73,
     "runs": [
      {
       "text": "\u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
       "accent": false,
       "k0": 0,
       "n": 11
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "ZenKakuGothicAntique-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     40.3,
     [
      100,
      100
     ],
     "lin"
    ]
   ],
   "rot": [
    [
     40.3,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     40.3,
     [
      540,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     40.3,
     0,
     "lin"
    ],
    [
     40.36666666666667,
     100,
     "lin"
    ],
    [
     42.23333333333333,
     100,
     "lin"
    ],
    [
     42.3,
     0,
     "lin"
    ]
   ],
   "bar": null,
   "blur": null,
   "motionBlur": false,
   "chStagger": 0.06,
   "chDur": 0.32
  }
 ],
 "cards": [
  {
   "t0": 7.22,
   "t1": 7.75,
   "bg": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "telop": {
    "name": "07.22 \u3044\u304f\u3089\uff1f",
    "t0": 7.22,
    "t1": 7.75,
    "lines": [
     {
      "size": 201,
      "runs": [
       {
        "text": "\u3044\u304f\u3089\uff1f",
        "accent": false,
        "k0": 0,
        "n": 4
       }
      ],
      "keys": {}
     }
    ],
    "anim": "cascade",
    "font": "ZenKakuGothicAntique-Black",
    "color": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "accent": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "border": false,
    "behind": false,
    "scale": [
     [
      7.22,
      [
       100,
       100
      ],
      "lin"
     ],
     [
      7.75,
      [
       103.0,
       103.0
      ],
      "lin"
     ]
    ],
    "rot": [
     [
      7.22,
      0.0,
      "lin"
     ]
    ],
    "pos": [
     [
      7.22,
      [
       540,
       960
      ],
      "lin"
     ]
    ],
    "opacity": [
     [
      7.63,
      100,
      "io"
     ],
     [
      7.75,
      0,
      "lin"
     ]
    ],
    "bar": null,
    "blur": null,
    "motionBlur": true,
    "chStagger": 0.04416666666666669,
    "chDur": 0.13250000000000006
   }
  },
  {
   "t0": 13.74,
   "t1": 14.38,
   "bg": [
    0.11764705882352941,
    0.10980392156862745,
    0.10196078431372549
   ],
   "telop": {
    "name": "13.74 \u5b89\u3044\u3093\u3058\u3083 \u306a\u3044\uff1f",
    "t0": 13.74,
    "t1": 14.38,
    "lines": [
     {
      "size": 160,
      "runs": [
       {
        "text": "\u5b89\u3044\u3093\u3058\u3083",
        "accent": false,
        "k0": 0,
        "n": 5
       }
      ],
      "keys": {
       "dx": [
        [
         13.74,
         -900,
         "fast"
        ],
        [
         14.08,
         0,
         "lin"
        ]
       ]
      }
     },
     {
      "size": 160,
      "runs": [
       {
        "text": "\u306a\u3044\uff1f",
        "accent": false,
        "k0": 5,
        "n": 3
       }
      ],
      "keys": {
       "dx": [
        [
         13.82,
         900,
         "fast"
        ],
        [
         14.16,
         0,
         "lin"
        ]
       ]
      }
     }
    ],
    "anim": "swipe",
    "font": "ZenKakuGothicAntique-Black",
    "color": [
     1.0,
     0.8235294117647058,
     0.12156862745098039
    ],
    "accent": [
     1.0,
     0.8235294117647058,
     0.12156862745098039
    ],
    "border": false,
    "behind": false,
    "scale": [
     [
      13.74,
      [
       100,
       100
      ],
      "lin"
     ],
     [
      14.38,
      [
       103.0,
       103.0
      ],
      "lin"
     ]
    ],
    "rot": [
     [
      13.74,
      0.0,
      "lin"
     ]
    ],
    "pos": [
     [
      13.74,
      [
       540,
       960
      ],
      "lin"
     ]
    ],
    "opacity": [
     [
      14.260000000000002,
      100,
      "io"
     ],
     [
      14.38,
      0,
      "lin"
     ]
    ],
    "bar": null,
    "blur": null,
    "motionBlur": true,
    "chStagger": 0.022857142857142878,
    "chDur": 0.16000000000000014
   }
  },
  {
   "t0": 26.04,
   "t1": 26.8,
   "bg": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "telop": {
    "name": "26.04 \u98df\u3079\u307e\u3059",
    "t0": 26.04,
    "t1": 26.8,
    "lines": [
     {
      "size": 201,
      "runs": [
       {
        "text": "\u98df\u3079\u307e\u3059",
        "accent": false,
        "k0": 0,
        "n": 4
       }
      ],
      "keys": {}
     }
    ],
    "anim": "zoom",
    "font": "ZenKakuGothicAntique-Black",
    "color": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "accent": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "border": false,
    "behind": false,
    "scale": [
     [
      26.04,
      [
       330,
       330
      ],
      "fast"
     ],
     [
      26.34,
      [
       100,
       100
      ],
      "lin"
     ],
     [
      26.8,
      [
       104.0,
       104.0
      ],
      "lin"
     ]
    ],
    "rot": [
     [
      26.04,
      0.0,
      "lin"
     ]
    ],
    "pos": [
     [
      26.04,
      [
       540,
       960
      ],
      "lin"
     ]
    ],
    "opacity": [
     [
      26.04,
      0,
      "lin"
     ],
     [
      26.106666666666666,
      100,
      "lin"
     ],
     [
      26.68,
      100,
      "io"
     ],
     [
      26.8,
      0,
      "lin"
     ]
    ],
    "bar": null,
    "blur": [
     [
      26.04,
      40,
      "fast"
     ],
     [
      26.34,
      0,
      "lin"
     ]
    ],
    "motionBlur": false,
    "chStagger": 0.06,
    "chDur": 0.1900000000000004
   }
  },
  {
   "t0": 39.68,
   "t1": 40.3,
   "bg": [
    0.11764705882352941,
    0.10980392156862745,
    0.10196078431372549
   ],
   "telop": {
    "name": "39.68 \u30ea\u30fc\u30ba\u30ca\u30d6\u30eb",
    "t0": 39.68,
    "t1": 40.3,
    "lines": [
     {
      "size": 134,
      "runs": [
       {
        "text": "\u30ea\u30fc\u30ba\u30ca\u30d6\u30eb",
        "accent": false,
        "k0": 0,
        "n": 6
       }
      ],
      "keys": {}
     }
    ],
    "anim": "popchars",
    "font": "ZenKakuGothicAntique-Black",
    "color": [
     1.0,
     0.8235294117647058,
     0.12156862745098039
    ],
    "accent": [
     1.0,
     0.8235294117647058,
     0.12156862745098039
    ],
    "border": false,
    "behind": false,
    "scale": [
     [
      39.68,
      [
       100,
       100
      ],
      "lin"
     ],
     [
      40.3,
      [
       103.0,
       103.0
      ],
      "lin"
     ]
    ],
    "rot": [
     [
      39.68,
      0.0,
      "lin"
     ]
    ],
    "pos": [
     [
      39.68,
      [
       540,
       960
      ],
      "lin"
     ]
    ],
    "opacity": [
     [
      40.18,
      100,
      "io"
     ],
     [
      40.3,
      0,
      "lin"
     ]
    ],
    "bar": null,
    "blur": null,
    "motionBlur": false,
    "chStagger": 0.03099999999999987,
    "chDur": 0.15499999999999936
   }
  }
 ],
 "behindSegments": [
  [
   36.18,
   37.4
  ]
 ],
 "fontPrefs": {
  "ZenKakuGothicAntique-Black": [
   "ToppanBunkyuMidashiGothicStdN-ExtraBold",
   "ToppanBunkyuMidashiGothicStd-ExtraBold",
   "ToppanBunkyuGothicPr6N-DB"
  ]
 },
 "safe": {
  "left": 60,
  "top": 250,
  "right": 960,
  "bottom": 1250
 },
 "tracking": -30,
 "border": 0.022,
 "lineGap": 0.12,
 "barH": 0.07,
 "dark": [
  0.11764705882352941,
  0.10980392156862745,
  0.10196078431372549
 ],
 "yellow": [
  1.0,
  0.8235294117647058,
  0.12156862745098039
 ],
 "hookEnd": 2.1,
 "hookDim": [
  [
   0,
   55.00000000000001,
   "lin"
  ],
  [
   1.85,
   55.00000000000001,
   "io"
  ],
  [
   2.1,
   0,
   "lin"
  ]
 ]
};
var MSG = {"intro": "IKEA\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0 \u7de8\u96c6\u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3092\u4f5c\u308a\u307e\u3059\u3002\nAdobe Fonts \u306e\u300c\u51f8\u7248\u6587\u4e45\u898b\u51fa\u3057\u30b4\u30b7\u30c3\u30af\u300d\u3092\u6709\u52b9\u306b\u3057\u3066\u304a\u304f\u3068\u3001\u305d\u308c\u304c\u4f7f\u308f\u308c\u307e\u3059\u3002\n\uff08\u7121\u3044\u5834\u5408\u306f fonts \u30d5\u30a9\u30eb\u30c0\u306e Zen Kaku Gothic Antique \u3092\u4f7f\u3044\u307e\u3059\u3002\u5148\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u304f\u3060\u3055\u3044\uff09\n\u6b21\u306e\u753b\u9762\u3067\u7d20\u6750\u52d5\u753b\uff08\u7de8\u96c6\u524d\u306e\u9ad8\u753b\u8cea\u7248\uff09\u3092\u9078\u3093\u3067\u304f\u3060\u3055\u3044\u3002", "pick": "\u7d20\u6750\u52d5\u753b\u3092\u9078\u629e", "fallback": "\u51f8\u7248\u6587\u4e45\u898b\u51fa\u3057\u30b4\u30b7\u30c3\u30af\u304c\u898b\u3064\u304b\u3089\u306a\u304b\u3063\u305f\u305f\u3081\u3001\u4ee3\u308f\u308a\u306e\u30d5\u30a9\u30f3\u30c8\u3092\u4f7f\u3044\u307e\u3057\u305f: ", "done": "\u5b8c\u6210\u3057\u307e\u3057\u305f\u3002\u8d64\u3044\u90e8\u5206\u306f\u30ea\u30fc\u30eb\u306eUI\u3067\u96a0\u308c\u308b\u7bc4\u56f2\u3067\u3059\uff08\u30ac\u30a4\u30c9\u30ec\u30a4\u30e4\u30fc\u306a\u306e\u3067\u66f8\u304d\u51fa\u3057\u306b\u306f\u5165\u308a\u307e\u305b\u3093\uff09\u3002"};
var W = 1080, H = 1920, FPS = 30;
var root = File($.fileName).parent;
var WARN = [];
var FONT_MAP = {};

// Use the first preferred font that is installed (Toppan Bunkyu via Adobe Fonts); otherwise the bundled one.
function resolveFonts(comp) {
    var probe = comp.layers.addText("\u3042");
    var src = probe.property("ADBE Text Properties").property("ADBE Text Document");
    for (var fb in DATA.fontPrefs) {
        var cands = DATA.fontPrefs[fb], chosen = fb;
        for (var i = 0; i < cands.length; i++) {
            try {
                var td = src.value; td.font = cands[i]; src.setValue(td);
                if (src.value.font === cands[i]) { chosen = cands[i]; break; }
            } catch (e) {}
        }
        FONT_MAP[fb] = chosen;
        if (chosen === fb) WARN.push(MSG.fallback + fb);
    }
    probe.remove();
}

function xf(L) { return L.property("ADBE Transform Group"); }
function setMax(prop, frac) { prop.setValue(prop.hasMax ? prop.maxValue * frac : frac * 100); }
function dims(prop) { var v = prop.value; return (v instanceof Array && !prop.isSpatial) ? v.length : 1; }
function easeArr(n, inf) { var a = []; for (var i = 0; i < n; i++) a.push(new KeyframeEase(0, inf)); return a; }

// keys: [[time, value, ease]]; ease of a key describes the segment that leaves it:
// "lin" linear, "fast" expo-like ease-out, "io" ease in-out.  conv(value) -> AE value.
function applyKeys(prop, keys, conv) {
    var i, n = dims(prop);
    for (i = 0; i < keys.length; i++) prop.setValueAtTime(keys[i][0], conv ? conv(keys[i][1]) : keys[i][1]);
    if (keys.length < 2) return;
    for (i = 1; i <= prop.numKeys; i++) {
        var outE = i <= keys.length ? keys[i - 1][2] : "lin";
        var inE = i > 1 ? keys[i - 2][2] : "lin";
        var linIn = inE === "lin", linOut = outE === "lin";
        var inInf = inE === "fast" ? 92 : 50, outInf = outE === "fast" ? 0.1 : 50;
        if (!linIn || !linOut) prop.setTemporalEaseAtKey(i, easeArr(n, linIn ? 33 : inInf), easeArr(n, linOut ? 33 : outInf));
        prop.setInterpolationTypeAtKey(i,
            linIn ? KeyframeInterpolationType.LINEAR : KeyframeInterpolationType.BEZIER,
            linOut ? KeyframeInterpolationType.LINEAR : KeyframeInterpolationType.BEZIER);
    }
    if (prop.isSpatial) for (i = 1; i <= prop.numKeys; i++) { try { prop.setSpatialAutoBezierAtKey(i, false); } catch (e) {} }
}
function sc3(v) { return (v instanceof Array) ? [v[0], v[1], 100] : [v, v, 100]; }
function dx3(v) { return [v, 0, 0]; }
function dy3(v) { return [0, v, 0]; }

function addShadow(L, size) {
    var ds = L.property("ADBE Effect Parade").addProperty("ADBE Drop Shadow");
    ds.property("ADBE Drop Shadow-0001").setValue([0, 0, 0, 1]);
    setMax(ds.property("ADBE Drop Shadow-0002"), 0.55);
    ds.property("ADBE Drop Shadow-0003").setValue(180);
    ds.property("ADBE Drop Shadow-0004").setValue(Math.max(2, size * 0.03));
    ds.property("ADBE Drop Shadow-0005").setValue(Math.max(4, size * 0.12));
}

function addRun(comp, text, size, color, border, fontName) {
    var L = comp.layers.addText(text);
    var src = L.property("ADBE Text Properties").property("ADBE Text Document");
    var td = src.value;
    try { td.resetCharStyle(); td.resetParagraphStyle(); } catch (e) {}
    td.font = FONT_MAP[fontName] || fontName; td.fontSize = size; td.tracking = DATA.tracking;
    td.applyFill = true; td.fillColor = color;
    if (border) {  // thin dark border drawn behind the fill
        td.applyStroke = true; td.strokeColor = DATA.dark; td.strokeOverFill = false;
        td.strokeWidth = Math.max(2, Math.round(size * DATA.border * 2));
    } else td.applyStroke = false;
    td.justification = ParagraphJustification.LEFT_JUSTIFY;
    src.setValue(td);
    if (border) addShadow(L, size);
    return L;
}

function animators(L) { return L.property("ADBE Text Properties").property("ADBE Text Animators"); }
function addAnimator(L, name, props) {
    animators(L).addProperty("ADBE Text Animator");
    var ai = animators(L).numProperties;
    animators(L).property(ai).name = name;
    for (var i = 0; i < props.length; i++)
        animators(L).property(ai).property("ADBE Text Animator Properties").addProperty(props[i]);
    return function (n) { return animators(L).property(ai).property("ADBE Text Animator Properties").property(n); };
}

// mask: the run rises from behind the lower edge of a layer mask (the mask does not move with the animator)
function addMaskRise(L, rect, size, keys) {
    var m = L.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var s = new Shape(), padX = size * 0.3, top = rect.top - size * 0.3, bot = rect.top + rect.height + size * 0.08;
    s.vertices = [[rect.left - padX, top], [rect.left + rect.width + padX, top],
                  [rect.left + rect.width + padX, bot], [rect.left - padX, bot]];
    s.closed = true;
    m.property("ADBE Mask Shape").setValue(s);
    var pr = addAnimator(L, "Rise", ["ADBE Text Position 3D"]);
    applyKeys(pr("ADBE Text Position 3D"), keys.dy, dy3);
}

// track: letter spacing collapses while fading in
function addTrackIn(L, keys) {
    var pr = addAnimator(L, "Track in", ["ADBE Text Tracking Amount", "ADBE Text Opacity"]);
    applyKeys(pr("ADBE Text Tracking Amount"), keys.tracking);
    applyKeys(pr("ADBE Text Opacity"), keys.opacity);
}

// swipe: the whole line slides in sideways (layer motion blur on)
function addSwipe(L, keys) {
    var pr = addAnimator(L, "Swipe", ["ADBE Text Position 3D"]);
    applyKeys(pr("ADBE Text Position 3D"), keys.dx, dx3);
}

// cascade / popchars: characters enter one after another (range selector offset sweeps left -> right)
function addChars(L, run, p, size) {
    var props = p.anim === "cascade" ? ["ADBE Text Position 3D", "ADBE Text Opacity"] : ["ADBE Text Scale 3D", "ADBE Text Opacity"];
    var pr = addAnimator(L, p.anim === "cascade" ? "Cascade" : "Pop chars", props);
    if (p.anim === "cascade") pr("ADBE Text Position 3D").setValue([0, -0.9 * size, 0]);
    else pr("ADBE Text Scale 3D").setValue([0, 0, 100]);
    pr("ADBE Text Opacity").setValue(0);
    var anims = animators(L), ai = anims.numProperties;
    var A = function () { return animators(L).property(ai); };
    A().property("ADBE Text Selectors").addProperty("ADBE Text Selector");
    var adv = A().property("ADBE Text Selectors").property(1).property("ADBE Text Range Advanced");
    adv.property("ADBE Text Range Shape").setValue(2);        // Ramp Up
    adv.property("ADBE Text Levels Max Ease").setValue(100);  // Ease High
    var off = A().property("ADBE Text Selectors").property(1).property("ADBE Text Percent Offset");
    var t0 = p.t0 + run.k0 * p.chStagger;
    applyKeys(off, [[t0, -100, "lin"], [t0 + p.chDur * 1.5 + p.chStagger * run.n, 100, "lin"]]);
}

// slot-machine digits: Source Text keyframes (hold)
function addCounter(L, keys) {
    var src = L.property("ADBE Text Properties").property("ADBE Text Document");
    for (var i = 0; i < keys.length; i++) {
        var td = src.value; td.text = keys[i][1];
        src.setValueAtTime(keys[i][0], td);
    }
}

function addBlurIn(L, keys) {
    var gb = L.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2");
    applyKeys(gb.property("ADBE Gaussian Blur 2-0001"), keys);
    try { gb.property("ADBE Gaussian Blur 2-0003").setValue(1); } catch (e) {}  // repeat edge pixels
}

function addBar(comp, nul, x, y, w, size, keys, t0, t1) {
    var L = comp.layers.addShape();
    var root = L.property("ADBE Root Vectors Group");
    root.addProperty("ADBE Vector Group");
    var g = function () { return root.property(1).property("ADBE Vectors Group"); };
    g().addProperty("ADBE Vector Shape - Rect"); g().addProperty("ADBE Vector Graphic - Fill");
    var h = Math.max(3, Math.round(size * DATA.barH));
    g().property(1).property("ADBE Vector Rect Size").setValue([w, h]);
    g().property(1).property("ADBE Vector Rect Position").setValue([w / 2, h / 2]);
    g().property(2).property("ADBE Vector Fill Color").setValue(DATA.yellow);
    L.parent = nul;
    xf(L).property("ADBE Anchor Point").setValue([0, 0]);
    xf(L).property("ADBE Position").setValue([x, y]);
    applyKeys(xf(L).property("ADBE Scale"), keys, function (v) { return [v, 100, 100]; });
    L.inPoint = t0; L.outPoint = t1;
    return L;
}

// One telop = a null (position / slow push-in) + one text layer per colour run.
function addPhrase(comp, p) {
    var nul = comp.layers.addNull(comp.duration);
    nul.name = "TELOP " + p.name;
    nul.startTime = 0; nul.inPoint = p.t0; nul.outPoint = p.t1;
    xf(nul).property("ADBE Anchor Point").setValue([0, 0, 0]);
    applyKeys(xf(nul).property("ADBE Position"), p.pos);
    applyKeys(xf(nul).property("ADBE Scale"), p.scale, sc3);
    applyKeys(xf(nul).property("ADBE Rotate Z"), p.rot);
    var lineBoxes = [], totalH = 0, li, k;
    for (li = 0; li < p.lines.length; li++) {
        var line = p.lines[li], lw = 0, top = 1e9, bot = -1e9, items = [];
        for (var ri = 0; ri < line.runs.length; ri++) {
            var run = line.runs[ri];
            var L = addRun(comp, run.text, line.size, run.accent ? p.accent : p.color, p.border, p.font);
            L.startTime = 0; L.inPoint = p.t0; L.outPoint = p.t1;
            var r = L.sourceRectAtTime(p.t1 - 0.01, false);
            items.push({ layer: L, rect: r, x: lw, run: run });
            lw += r.width + line.size * DATA.tracking / 1000;
            top = Math.min(top, r.top); bot = Math.max(bot, r.top + r.height);
        }
        lineBoxes.push({ items: items, width: lw - line.size * DATA.tracking / 1000, top: top, bot: bot,
                         size: line.size, keys: line.keys });
        totalH += (bot - top) + (li ? line.size * DATA.lineGap : 0);
    }
    var y = -totalH / 2;
    for (li = 0; li < lineBoxes.length; li++) {
        var lb = lineBoxes[li];
        if (li) y += lb.size * DATA.lineGap;
        for (k = 0; k < lb.items.length; k++) {
            var it = lb.items[k];
            it.layer.parent = nul;
            xf(it.layer).property("ADBE Position").setValue([-lb.width / 2 + it.x - it.rect.left, y - lb.top]);
            it.layer.name = "  " + p.name + " / " + (li + 1) + "-" + (k + 1);
            applyKeys(xf(it.layer).property("ADBE Opacity"), p.opacity);
            try {
                if (p.anim === "mask") addMaskRise(it.layer, it.rect, lb.size, lb.keys);
                else if (p.anim === "track") addTrackIn(it.layer, lb.keys);
                else if (p.anim === "swipe") addSwipe(it.layer, lb.keys);
                else if (p.anim === "cascade" || p.anim === "popchars") addChars(it.layer, it.run, p, lb.size);
                if (p.blur) addBlurIn(it.layer, p.blur);
                if (it.run.counter) addCounter(it.layer, it.run.counter);
                if (p.motionBlur || p.anim === "swipe") it.layer.motionBlur = true;
            } catch (e) { WARN.push(p.name + ": " + e.toString()); }
        }
        y += lb.bot - lb.top;
        if (p.bar && li === lineBoxes.length - 1) {
            try {
                var bar = addBar(comp, nul, -lb.width / 2, y + lb.size * 0.08, lb.width, lb.size, p.bar, p.t0, p.t1);
                bar.name = "  " + p.name + " / underline";
                applyKeys(xf(bar).property("ADBE Opacity"), p.opacity);
            } catch (e2) { WARN.push(p.name + " underline: " + e2.toString()); }
        }
    }
    return nul;
}

// ---------- shape helpers
function shapeLayer(comp, name) {
    var L = comp.layers.addShape(); L.name = name;
    xf(L).property("ADBE Position").setValue([0, 0]);
    return L;
}
function addRect(L, cx, cy, w, h, color, opacity) {
    var root = L.property("ADBE Root Vectors Group");
    root.addProperty("ADBE Vector Group");
    var gi = root.numProperties;
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Rect");
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Graphic - Fill");
    var c = root.property(gi).property("ADBE Vectors Group");
    c.property(1).property("ADBE Vector Rect Size").setValue([w, h]);
    c.property(2).property("ADBE Vector Fill Color").setValue(color);
    c.property(2).property("ADBE Vector Fill Opacity").setValue(opacity);
    root.property(gi).property("ADBE Vector Transform Group").property("ADBE Vector Position").setValue([cx, cy]);
}

function addCard(comp, c, idx) {
    var solid = comp.layers.addSolid(c.bg, "CARD " + idx + " bg", W, H, 1, comp.duration);
    solid.inPoint = c.t0; solid.outPoint = c.t1;
    var st = shapeLayer(comp, "CARD " + idx + " light");
    for (var k = -6; k <= 6; k++) addRect(st, 540, 960 + k * 320, 3200, 140, k % 2 ? [1, 1, 1] : [0, 0, 0], 7);
    xf(st).property("ADBE Anchor Point").setValue([540, 960]);
    xf(st).property("ADBE Rotate Z").setValue(-30);
    xf(st).property("ADBE Position").setValuesAtTimes([c.t0, c.t1], [[540, 960], [590, 990]]);
    st.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2").property("ADBE Gaussian Blur 2-0001").setValue(90);
    st.inPoint = c.t0; st.outPoint = c.t1;
    addPhrase(comp, c.telop);
}

function addSafeGuide(comp) {
    var g = shapeLayer(comp, "GUIDE  Reels safe zone (not rendered)");
    var s = DATA.safe, red = [1, 0.15, 0.15];
    addRect(g, W / 2, s.top / 2, W, s.top, red, 25);
    addRect(g, W / 2, (s.bottom + H) / 2, W, H - s.bottom, red, 25);
    addRect(g, s.left / 2, (s.top + s.bottom) / 2, s.left, s.bottom - s.top, red, 25);
    addRect(g, (s.right + W) / 2, (s.top + s.bottom) / 2, W - s.right, s.bottom - s.top, red, 25);
    g.guideLayer = true;
}

function importFile(path) {
    var f = new File(path);
    if (!f.exists) return null;
    return app.project.importFile(new ImportOptions(f));
}

// ---------------------------------------------------------- build
app.beginUndoGroup("IKEA soft-ice edit");
try {
    if (!app.project) app.newProject();
    alert(MSG.intro);
    var srcFile = File.openDialog(MSG.pick);
    var folder = app.project.items.addFolder("IKEA_edit");
    var comp = app.project.items.addComp("IKEA_SoftCream_Reel", W, H, 1, DATA.duration, FPS);
    comp.parentFolder = folder;
    comp.motionBlur = true;
    comp.bgColor = [0, 0, 0];
    resolveFonts(comp);

    var srcItem = srcFile ? app.project.importFile(new ImportOptions(srcFile)) : null;
    if (srcItem) srcItem.parentFolder = folder;
    function addFootage(name) {
        var L = srcItem ? comp.layers.add(srcItem) : comp.layers.addSolid([0.5, 0.5, 0.5], "REPLACE ME footage", W, H, 1, DATA.duration);
        L.name = name;
        if (srcItem && srcItem.width) {
            var s = Math.max(W / srcItem.width, H / srcItem.height) * 100;
            xf(L).property("ADBE Scale").setValue([s, s, 100]);
        }
        return L;
    }
    addFootage("FOOTAGE (base)");

    // darken the opening shot so the hook reads
    var dim = comp.layers.addSolid([0, 0, 0], "HOOK dim", W, H, 1, comp.duration);
    dim.inPoint = 0; dim.outPoint = DATA.hookEnd;
    applyKeys(xf(dim).property("ADBE Opacity"), DATA.hookDim);

    var i;
    for (i = 0; i < DATA.telops.length; i++) if (DATA.telops[i].behind) addPhrase(comp, DATA.telops[i]);

    var matteItem = importFile(root.fsName + "/matte/person_matte.mp4");
    if (matteItem) matteItem.parentFolder = folder;
    for (var sgi = 0; sgi < DATA.behindSegments.length; sgi++) {
        var seg = DATA.behindSegments[sgi];
        var cut = addFootage("PERSON cut-out " + (sgi + 1));
        if (srcItem) cut.audioEnabled = false;
        cut.inPoint = seg[0]; cut.outPoint = seg[1];
        if (matteItem) {
            var mt = comp.layers.add(matteItem);
            mt.name = "PERSON matte " + (sgi + 1) + " (luma)";
            mt.inPoint = seg[0]; mt.outPoint = seg[1];
            if (mt.hasAudio) mt.audioEnabled = false;
            if (typeof cut.setTrackMatte === "function") { cut.setTrackMatte(mt, TrackMatteType.LUMA); mt.enabled = false; }
            else { mt.moveBefore(cut); cut.trackMatteType = TrackMatteType.LUMA; }
        }
    }

    for (i = 0; i < DATA.telops.length; i++) if (!DATA.telops[i].behind) addPhrase(comp, DATA.telops[i]);
    for (i = 0; i < DATA.cards.length; i++) addCard(comp, DATA.cards[i], i + 1);

    var sfx = importFile(root.fsName + "/sfx/sfx_mix.wav");
    if (sfx) { sfx.parentFolder = folder; var sl = comp.layers.add(sfx); sl.name = "SFX mix"; }

    addSafeGuide(comp);
    comp.openInViewer();
    alert(MSG.done + (WARN.length ? "\n\n" + WARN.slice(0, 8).join("\n") : ""));
} catch (err) {
    alert("Error: " + err.toString() + " (line " + err.line + ")");
}
app.endUndoGroup();
})();
