// IKEA soft-ice vlog - After Effects builder (generated by ikea_ae_build.py)
// Run in After Effects: File > Scripts > Run Script File...
(function () {
var DATA = {
 "duration": 42.233,
 "telops": [
  {
   "name": "00.20 \u30b9\u30a6\u30a7\u30fc\u30c7\u30f3\u306e \u30a4\u30b1\u30a2\u3092",
   "t0": 0.2,
   "t1": 2.1,
   "x": 510,
   "y": 700,
   "rot": 0.0,
   "lines": [
    {
     "size": 100,
     "runs": [
      {
       "text": "\u30b9\u30a6\u30a7\u30fc\u30c7\u30f3\u306e",
       "accent": false
      }
     ]
    },
    {
     "size": 226,
     "runs": [
      {
       "text": "\u30a4\u30b1\u30a2",
       "accent": true
      },
      {
       "text": "\u3092",
       "accent": false
      }
     ]
    }
   ],
   "anim": "fly",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 650,
   "dur": 0.3,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "00.76 \u898b\u3064\u3051\u305f\u3093\u3067",
   "t0": 0.76,
   "t1": 1.18,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u898b\u3064\u3051\u305f\u3093\u3067",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "01.18 \u884c\u3063\u3066\u307f\u305f\u3044\u3068\u601d\u3044\u307e\u3059",
   "t0": 1.18,
   "t1": 2.1,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 82,
     "runs": [
      {
       "text": "\u884c\u3063\u3066\u307f\u305f\u3044\u3068\u601d\u3044\u307e\u3059",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "02.38 \u65e5\u672c\u3060\u3068",
   "t0": 2.38,
   "t1": 2.84,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u65e5\u672c\u3060\u3068",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "02.84 \u30a4\u30b1\u30a2\u306e",
   "t0": 2.84,
   "t1": 3.16,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a4\u30b1\u30a2\u306e",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "03.16 \u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
   "t0": 3.16,
   "t1": 3.7,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "03.70 1\u500b50\u5186",
   "t0": 3.7,
   "t1": 4.38,
   "x": 510,
   "y": 985,
   "rot": 0.0,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false
      },
      {
       "text": "50\u5186",
       "accent": true
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "04.38 \u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
   "t0": 4.38,
   "t1": 5.2,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "05.66 \u5b9f\u969b",
   "t0": 5.66,
   "t1": 6.02,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b9f\u969b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "06.02 \u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
   "t0": 6.02,
   "t1": 7.22,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "07.75 \u8cb7\u3048\u308b\u306e\u304b\u3092",
   "t0": 7.75,
   "t1": 8.04,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8cb7\u3048\u308b\u306e\u304b\u3092",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "08.04 \u898b\u3066\u307f\u307e\u3059",
   "t0": 8.04,
   "t1": 8.8,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u898b\u3066\u307f\u307e\u3059",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "08.98 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 8.98,
   "t1": 10.22,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "10.22 9\u306a\u3093\u3067",
   "t0": 10.22,
   "t1": 11.74,
   "x": 510,
   "y": 985,
   "rot": -2,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "9",
       "accent": true
      },
      {
       "text": "\u306a\u3093\u3067",
       "accent": false
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "11.74 150\u5186",
   "t0": 11.74,
   "t1": 12.96,
   "x": 480,
   "y": 950,
   "rot": 0.0,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "150\u5186",
       "accent": true
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "12.10 \u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
   "t0": 12.1,
   "t1": 12.96,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "12.96 \u3053\u308c\u666e\u901a\u306b",
   "t0": 12.96,
   "t1": 13.74,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c\u666e\u901a\u306b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "13.74 \u5b89\u3044\u3093\u3058\u3083\u306a\u3044\uff1f",
   "t0": 13.74,
   "t1": 14.38,
   "x": 510,
   "y": 985,
   "rot": -3,
   "lines": [
    {
     "size": 113,
     "runs": [
      {
       "text": "\u5b89\u3044",
       "accent": true
      },
      {
       "text": "\u3093\u3058\u3083\u306a\u3044\uff1f",
       "accent": false
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "14.38 \u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
   "t0": 14.38,
   "t1": 15.54,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "15.54 1\u500b112\u5186",
   "t0": 15.54,
   "t1": 16.72,
   "x": 510,
   "y": 985,
   "rot": 0.0,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false
      },
      {
       "text": "112\u5186",
       "accent": true
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "16.72 \u3067\u8cb7\u3048\u307e\u3059\u306d",
   "t0": 16.72,
   "t1": 17.5,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3067\u8cb7\u3048\u307e\u3059\u306d",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "17.76 \u30bb\u30c3\u30c8\u3057\u3066",
   "t0": 17.76,
   "t1": 18.8,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bb\u30c3\u30c8\u3057\u3066",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "19.16 \u3042\u3068\u306f\u3053\u3053\u3092",
   "t0": 19.16,
   "t1": 20.08,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u3068\u306f\u3053\u3053\u3092",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "20.08 \u62bc\u3059\u3060\u3051\u3067\u3059\u306d",
   "t0": 20.08,
   "t1": 21.0,
   "x": 510,
   "y": 985,
   "rot": 2,
   "lines": [
    {
     "size": 129,
     "runs": [
      {
       "text": "\u62bc\u3059\u3060\u3051",
       "accent": true
      },
      {
       "text": "\u3067\u3059\u306d",
       "accent": false
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "23.04 \u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
   "t0": 23.04,
   "t1": 24.0,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "24.84 \u5b9f\u969b\u306b",
   "t0": 24.84,
   "t1": 26.04,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b9f\u969b\u306b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "26.04 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0 \u98df\u3079\u307e\u3059",
   "t0": 26.04,
   "t1": 26.95,
   "x": 510,
   "y": 985,
   "rot": 0.0,
   "lines": [
    {
     "size": 90,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ]
    },
    {
     "size": 190,
     "runs": [
      {
       "text": "\u98df\u3079\u307e\u3059",
       "accent": true
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "29.48 \u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
   "t0": 29.48,
   "t1": 30.48,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "30.48 \u77ac\u9593\u306b",
   "t0": 30.48,
   "t1": 31.3,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u77ac\u9593\u306b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "31.90 \u3046\u308f\u3063\uff01\u3063\u3066",
   "t0": 31.9,
   "t1": 32.78,
   "x": 530,
   "y": 985,
   "rot": -4,
   "lines": [
    {
     "size": 151,
     "runs": [
      {
       "text": "\u3046\u308f\u3063\uff01",
       "accent": true
      },
      {
       "text": "\u3063\u3066",
       "accent": false
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "32.78 \u8272\u3005\u3046\u307e\u3044",
   "t0": 32.78,
   "t1": 33.68,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8272\u3005\u3046\u307e\u3044",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "33.68 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 33.68,
   "t1": 34.16,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "34.16 \u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
   "t0": 34.16,
   "t1": 35.0,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "35.14 \u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
   "t0": 35.14,
   "t1": 36.18,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "36.18 5\u500d\u6fc3\u7e2e",
   "t0": 36.18,
   "t1": 37.4,
   "x": 510,
   "y": 400,
   "rot": 0.0,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "5\u500d\u6fc3\u7e2e",
       "accent": true
      }
     ]
    }
   ],
   "anim": "cascade",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 260,
   "dur": 0.3,
   "stagger": 0.07,
   "behind": true
  },
  {
   "name": "36.84 \u3057\u305f\u307f\u305f\u3044\u306a",
   "t0": 36.84,
   "t1": 37.28,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3057\u305f\u307f\u305f\u3044\u306a",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "37.28 \u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
   "t0": 37.28,
   "t1": 38.0,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "38.00 \u3053\u308c",
   "t0": 38.0,
   "t1": 38.6,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "39.24 \u610f\u5916\u3068\u306d",
   "t0": 39.24,
   "t1": 39.68,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u610f\u5916\u3068\u306d",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "39.68 \u30ea\u30fc\u30ba\u30ca\u30d6\u30eb\u306a\u306e\u3067",
   "t0": 39.68,
   "t1": 40.42,
   "x": 510,
   "y": 985,
   "rot": 0.0,
   "lines": [
    {
     "size": 100,
     "runs": [
      {
       "text": "\u30ea\u30fc\u30ba\u30ca\u30d6\u30eb",
       "accent": true
      },
      {
       "text": "\u306a\u306e\u3067",
       "accent": false
      }
     ]
    }
   ],
   "anim": "pop",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  },
  {
   "name": "40.42 \u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
   "t0": 40.42,
   "t1": 42.3,
   "x": 510,
   "y": 1150,
   "rot": 0.0,
   "lines": [
    {
     "size": 82,
     "runs": [
      {
       "text": "\u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
       "accent": false
      }
     ]
    }
   ],
   "anim": "settle",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "frm": [
    0,
    -1
   ],
   "dist": 500,
   "dur": 0.22,
   "stagger": 0.06,
   "behind": false
  }
 ],
 "cards": [
  {
   "t0": 7.22,
   "t1": 7.75,
   "bg": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "telop": {
    "name": "07.22 \u3044\u304f\u3089\uff1f",
    "t0": 7.22,
    "t1": 7.75,
    "x": 510,
    "y": 760,
    "rot": 0.0,
    "lines": [
     {
      "size": 226,
      "runs": [
       {
        "text": "\u3044\u304f\u3089\uff1f",
        "accent": false
       }
      ]
     }
    ],
    "anim": "pop",
    "color": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "accent": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "frm": [
     0,
     -1
    ],
    "dist": 500,
    "dur": 0.2,
    "stagger": 0.06,
    "behind": false
   }
  }
 ],
 "behindSegments": [
  [
   36.18,
   37.4
  ]
 ],
 "safe": {
  "left": 60,
  "top": 250,
  "right": 960,
  "bottom": 1250
 },
 "font": "RoundedMplus1c-Black",
 "tracking": -30,
 "border": 0.045,
 "dark": [
  0.11764705882352941,
  0.10980392156862745,
  0.10196078431372549
 ]
};
var MSG = {"intro": "IKEA\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0 \u7de8\u96c6\u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3092\u4f5c\u308a\u307e\u3059\u3002\n\u5148\u306b fonts \u30d5\u30a9\u30eb\u30c0\u306e\u30d5\u30a9\u30f3\u30c8\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u304a\u3044\u3066\u304f\u3060\u3055\u3044\u3002\n\u6b21\u306e\u753b\u9762\u3067\u7d20\u6750\u52d5\u753b\uff08\u7de8\u96c6\u524d\u306e\u9ad8\u753b\u8cea\u7248\uff09\u3092\u9078\u3093\u3067\u304f\u3060\u3055\u3044\u3002", "pick": "\u7d20\u6750\u52d5\u753b\u3092\u9078\u629e", "done": "\u5b8c\u6210\u3057\u307e\u3057\u305f\u3002\u8d64\u3044\u90e8\u5206\u306f\u30ea\u30fc\u30eb\u306eUI\u3067\u96a0\u308c\u308b\u7bc4\u56f2\u3067\u3059\uff08\u30ac\u30a4\u30c9\u30ec\u30a4\u30e4\u30fc\u306a\u306e\u3067\u66f8\u304d\u51fa\u3057\u306b\u306f\u5165\u308a\u307e\u305b\u3093\uff09\u3002"};
var W = 1080, H = 1920, FPS = 30;
var root = File($.fileName).parent;

function ease(prop, k, inInf, outInf) {
    var n = (prop.value instanceof Array && !prop.isSpatial) ? prop.value.length : 1;
    var ins = [], outs = [];
    for (var i = 0; i < n; i++) { ins.push(new KeyframeEase(0, inInf)); outs.push(new KeyframeEase(0, outInf)); }
    prop.setTemporalEaseAtKey(k, ins, outs);
}
function expoOut(prop) { ease(prop, 1, 33, 0.1); ease(prop, 2, 92, 33); }
function setMax(prop, frac) { prop.setValue(prop.hasMax ? prop.maxValue * frac : frac * 100); }
function xf(L) { return L.property("ADBE Transform Group"); }

// tight dark halo: keeps white / yellow readable on bright shots
function addHalo(L, size) {
    var ds = L.property("ADBE Effect Parade").addProperty("ADBE Drop Shadow");
    ds.property("ADBE Drop Shadow-0001").setValue([0, 0, 0, 1]);
    setMax(ds.property("ADBE Drop Shadow-0002"), 0.8);
    ds.property("ADBE Drop Shadow-0003").setValue(180);
    ds.property("ADBE Drop Shadow-0004").setValue(Math.max(2, size * 0.03));
    ds.property("ADBE Drop Shadow-0005").setValue(Math.max(6, size * 0.14));
}

function addRun(comp, text, size, color, halo) {
    // halo == true: dark border (stroke behind fill) + soft shadow
    var L = comp.layers.addText(text);
    var src = L.property("ADBE Text Properties").property("ADBE Text Document");
    var td = src.value;
    try { td.resetCharStyle(); td.resetParagraphStyle(); } catch (e) {}
    td.font = DATA.font; td.fontSize = size; td.tracking = DATA.tracking;
    td.applyFill = true; td.fillColor = color;
    if (halo) {
        td.applyStroke = true; td.strokeColor = DATA.dark; td.strokeOverFill = false;
        td.strokeWidth = Math.max(4, Math.round(size * DATA.border * 2));
    } else td.applyStroke = false;
    td.justification = ParagraphJustification.LEFT_JUSTIFY;
    src.setValue(td);
    if (halo) addHalo(L, size);
    return L;
}

// One telop = a null (position / rotation / scale animation) + one text layer per colour run.
function addPhrase(comp, p, halo) {
    var nul = comp.layers.addNull(comp.duration);
    nul.name = "TELOP " + p.name;
    nul.startTime = 0; nul.inPoint = p.t0; nul.outPoint = p.t1;
    xf(nul).property("ADBE Anchor Point").setValue([0, 0, 0]);
    xf(nul).property("ADBE Position").setValue([p.x, p.y]);
    xf(nul).property("ADBE Rotate Z").setValue(p.rot);
    var runs = [], lineBoxes = [], totalH = 0;
    for (var li = 0; li < p.lines.length; li++) {
        var line = p.lines[li], lw = 0, top = 1e9, bot = -1e9, items = [];
        for (var ri = 0; ri < line.runs.length; ri++) {
            var run = line.runs[ri];
            var L = addRun(comp, run.text, line.size, run.accent ? p.accent : p.color, halo);
            L.startTime = 0; L.inPoint = p.t0; L.outPoint = p.t1;
            var r = L.sourceRectAtTime(p.t0, false);
            items.push({ layer: L, rect: r, x: lw });
            lw += r.width + line.size * DATA.tracking / 1000;
            top = Math.min(top, r.top); bot = Math.max(bot, r.top + r.height);
        }
        lineBoxes.push({ items: items, width: lw - line.size * DATA.tracking / 1000, top: top, bot: bot, size: line.size });
        totalH += (bot - top) + (li ? line.size * 0.12 : 0);
    }
    var y = -totalH / 2;
    for (var lj = 0; lj < lineBoxes.length; lj++) {
        var lb = lineBoxes[lj];
        if (lj) y += lb.size * 0.12;
        var baseline = y - lb.top;
        for (var k = 0; k < lb.items.length; k++) {
            var it = lb.items[k];
            it.layer.parent = nul;
            xf(it.layer).property("ADBE Position").setValue([-lb.width / 2 + it.x - it.rect.left, baseline]);
            it.layer.name = "  " + p.name + " / " + (lj + 1) + "-" + (k + 1);
            runs.push(it.layer);
        }
        y += lb.bot - lb.top;
    }
    animate(comp, p, nul, runs);
    return nul;
}

function animate(comp, p, nul, runs) {
    var t0 = p.t0, t1 = p.t0 + p.dur, i;
    var sc = xf(nul).property("ADBE Scale");
    if (p.anim === "settle") {
        sc.setValuesAtTimes([t0, t0 + 0.15], [[105, 105, 100], [100, 100, 100]]); expoOut(sc);
    } else if (p.anim === "pop") {
        sc.setValuesAtTimes([t0, t0 + p.dur * 0.6, t1], [[70, 70, 100], [106, 106, 100], [100, 100, 100]]);
        ease(sc, 1, 33, 0.1); ease(sc, 2, 50, 50); ease(sc, 3, 80, 33);
    } else if (p.anim === "fly") {
        var pos = xf(nul).property("ADBE Position");
        pos.setValuesAtTimes([t0, t1], [[p.x + p.frm[0] * p.dist, p.y + p.frm[1] * p.dist], [p.x, p.y]]);
        expoOut(pos);
        for (i = 0; i < runs.length; i++) runs[i].motionBlur = true;
    } else if (p.anim === "cascade") {
        for (i = 0; i < runs.length; i++) {
            var L = runs[i];
            L.motionBlur = true;
            var anims = L.property("ADBE Text Properties").property("ADBE Text Animators");
            anims.addProperty("ADBE Text Animator");
            var A = function () { return L.property("ADBE Text Properties").property("ADBE Text Animators").property(1); };
            A().name = "Cascade";
            A().property("ADBE Text Animator Properties").addProperty("ADBE Text Position 3D");
            A().property("ADBE Text Animator Properties").addProperty("ADBE Text Opacity");
            A().property("ADBE Text Animator Properties").property("ADBE Text Position 3D").setValue([0, -p.dist, 0]);
            A().property("ADBE Text Animator Properties").property("ADBE Text Opacity").setValue(0);
            A().property("ADBE Text Selectors").addProperty("ADBE Text Selector");
            var adv = A().property("ADBE Text Selectors").property(1).property("ADBE Text Range Advanced");
            adv.property("ADBE Text Range Shape").setValue(2);       // Ramp Up
            adv.property("ADBE Text Levels Max Ease").setValue(100); // Ease High
            var off = A().property("ADBE Text Selectors").property(1).property("ADBE Text Percent Offset");
            off.setValuesAtTimes([t0, t0 + p.dur + p.stagger * 4], [-100, 100]);
            ease(off, 1, 33, 0.1); ease(off, 2, 75, 33);
        }
    }
}

// ---------- shape helpers
function shapeLayer(comp, name) {
    var L = comp.layers.addShape(); L.name = name;
    xf(L).property("ADBE Position").setValue([0, 0]);
    return L;
}
function addRect(L, cx, cy, w, h, color, opacity) {
    var root = L.property("ADBE Root Vectors Group");
    root.addProperty("ADBE Vector Group");
    var gi = root.numProperties;
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Rect");
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Graphic - Fill");
    var c = root.property(gi).property("ADBE Vectors Group");
    c.property(1).property("ADBE Vector Rect Size").setValue([w, h]);
    c.property(2).property("ADBE Vector Fill Color").setValue(color);
    c.property(2).property("ADBE Vector Fill Opacity").setValue(opacity);
    root.property(gi).property("ADBE Vector Transform Group").property("ADBE Vector Position").setValue([cx, cy]);
}

function addCard(comp, c, idx) {
    var solid = comp.layers.addSolid(c.bg, "CARD " + idx + " bg", W, H, 1, comp.duration);
    solid.inPoint = c.t0; solid.outPoint = c.t1;
    var st = shapeLayer(comp, "CARD " + idx + " light");
    for (var k = -6; k <= 6; k++) addRect(st, 540, 960 + k * 320, 3200, 140, k % 2 ? [1, 1, 1] : [0, 0, 0], 7);
    xf(st).property("ADBE Anchor Point").setValue([540, 960]);
    xf(st).property("ADBE Rotate Z").setValue(-30);
    xf(st).property("ADBE Position").setValuesAtTimes([c.t0, c.t1], [[540, 960], [590, 990]]);
    st.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2").property("ADBE Gaussian Blur 2-0001").setValue(90);
    st.inPoint = c.t0; st.outPoint = c.t1;
    addPhrase(comp, c.telop, false);
}

function addSafeGuide(comp) {
    var g = shapeLayer(comp, "GUIDE  Reels safe zone (not rendered)");
    var s = DATA.safe, red = [1, 0.15, 0.15];
    addRect(g, W / 2, s.top / 2, W, s.top, red, 25);
    addRect(g, W / 2, (s.bottom + H) / 2, W, H - s.bottom, red, 25);
    addRect(g, s.left / 2, (s.top + s.bottom) / 2, s.left, s.bottom - s.top, red, 25);
    addRect(g, (s.right + W) / 2, (s.top + s.bottom) / 2, W - s.right, s.bottom - s.top, red, 25);
    g.guideLayer = true;
}

function importFile(path) {
    var f = new File(path);
    if (!f.exists) return null;
    return app.project.importFile(new ImportOptions(f));
}

// ---------------------------------------------------------- build
app.beginUndoGroup("IKEA soft-ice edit");
try {
    if (!app.project) app.newProject();
    alert(MSG.intro);
    var srcFile = File.openDialog(MSG.pick);
    var folder = app.project.items.addFolder("IKEA_edit");
    var comp = app.project.items.addComp("IKEA_SoftCream_Reel", W, H, 1, DATA.duration, FPS);
    comp.parentFolder = folder;
    comp.motionBlur = true;
    comp.bgColor = [0, 0, 0];

    var srcItem = srcFile ? app.project.importFile(new ImportOptions(srcFile)) : null;
    if (srcItem) srcItem.parentFolder = folder;
    function addFootage(name) {
        var L = srcItem ? comp.layers.add(srcItem) : comp.layers.addSolid([0.5, 0.5, 0.5], "REPLACE ME footage", W, H, 1, DATA.duration);
        L.name = name;
        if (srcItem && srcItem.width) {
            var s = Math.max(W / srcItem.width, H / srcItem.height) * 100;
            xf(L).property("ADBE Scale").setValue([s, s, 100]);
        }
        return L;
    }
    addFootage("FOOTAGE (base)");

    var i;
    for (i = 0; i < DATA.telops.length; i++) if (DATA.telops[i].behind) addPhrase(comp, DATA.telops[i], true);

    var matteItem = importFile(root.fsName + "/matte/person_matte.mp4");
    if (matteItem) matteItem.parentFolder = folder;
    for (var sgi = 0; sgi < DATA.behindSegments.length; sgi++) {
        var seg = DATA.behindSegments[sgi];
        var cut = addFootage("PERSON cut-out " + (sgi + 1));
        if (srcItem) cut.audioEnabled = false;
        cut.inPoint = seg[0]; cut.outPoint = seg[1];
        if (matteItem) {
            var mt = comp.layers.add(matteItem);
            mt.name = "PERSON matte " + (sgi + 1) + " (luma)";
            mt.inPoint = seg[0]; mt.outPoint = seg[1];
            if (mt.hasAudio) mt.audioEnabled = false;
            if (typeof cut.setTrackMatte === "function") { cut.setTrackMatte(mt, TrackMatteType.LUMA); mt.enabled = false; }
            else { mt.moveBefore(cut); cut.trackMatteType = TrackMatteType.LUMA; }
        }
    }

    for (i = 0; i < DATA.telops.length; i++) if (!DATA.telops[i].behind) addPhrase(comp, DATA.telops[i], true);
    for (i = 0; i < DATA.cards.length; i++) addCard(comp, DATA.cards[i], i + 1);

    var sfx = importFile(root.fsName + "/sfx/sfx_mix.wav");
    if (sfx) { sfx.parentFolder = folder; var sl = comp.layers.add(sfx); sl.name = "SFX mix"; }

    addSafeGuide(comp);
    comp.openInViewer();
    alert(MSG.done);
} catch (err) {
    alert("Error: " + err.toString() + " (line " + err.line + ")");
}
app.endUndoGroup();
})();
