// IKEA soft-ice vlog - After Effects builder (generated by ikea_ae_build.py)
// Run in After Effects: File > Scripts > Run Script File...
(function () {
var DATA = {
 "duration": 42.233,
 "telops": [
  {
   "name": "00.10 \u65e5\u672c\u306750\u5186\u306e",
   "t0": 0.1,
   "t1": 2.1,
   "lines": [
    {
     "size": 70,
     "runs": [
      {
       "text": "\u65e5\u672c\u306750\u5186\u306e",
       "accent": false
      }
     ],
     "keys": {
      "tracking": [
       [
        0.1,
        350,
        "fast"
       ],
       [
        0.7,
        0,
        "lin"
       ]
      ],
      "opacity": [
       [
        0.1,
        0,
        "io"
       ],
       [
        0.45999999999999996,
        100,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "track",
   "font": "ShipporiMinchoB1-ExtraBold",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.1,
     100,
     "lin"
    ],
    [
     2.1,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     0.1,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.1,
     [
      510,
      470
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "00.28 \u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0",
   "t0": 0.28,
   "t1": 2.1,
   "lines": [
    {
     "size": 110,
     "runs": [
      {
       "text": "\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ],
     "keys": {
      "dy": [
       [
        0.28,
        126.49999999999999,
        "fast"
       ],
       [
        0.7,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.28,
     100,
     "lin"
    ],
    [
     2.1,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     0.28,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.28,
     [
      510,
      590
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "00.55 \u672c\u5834\u3060\u3068",
   "t0": 0.55,
   "t1": 2.1,
   "lines": [
    {
     "size": 70,
     "runs": [
      {
       "text": "\u672c\u5834\u3060\u3068",
       "accent": false
      }
     ],
     "keys": {
      "tracking": [
       [
        0.55,
        350,
        "fast"
       ],
       [
        1.15,
        0,
        "lin"
       ]
      ],
      "opacity": [
       [
        0.55,
        0,
        "io"
       ],
       [
        0.91,
        100,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "track",
   "font": "ShipporiMinchoB1-ExtraBold",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.55,
     100,
     "lin"
    ],
    [
     2.1,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     0.55,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.55,
     [
      510,
      735
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "00.75 \u3044\u304f\u3089\uff1f",
   "t0": 0.75,
   "t1": 2.1,
   "lines": [
    {
     "size": 206,
     "runs": [
      {
       "text": "\u3044\u304f\u3089\uff1f",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        0.75,
        236.89999999999998,
        "fast"
       ],
       [
        1.17,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.75,
     100,
     "lin"
    ],
    [
     2.1,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     0.75,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.75,
     [
      510,
      880
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.85,
     100,
     "io"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     0.9299999999999999,
     0,
     "fast"
    ],
    [
     1.33,
     100,
     "lin"
    ]
   ]
  },
  {
   "name": "00.76 \u898b\u3064\u3051\u305f\u3093\u3067",
   "t0": 0.76,
   "t1": 1.18,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u898b\u3064\u3051\u305f\u3093\u3067",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     0.76,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     0.76,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     0.76,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     0.76,
     0,
     "lin"
    ],
    [
     0.8266666666666667,
     100,
     "lin"
    ],
    [
     1.1133333333333333,
     100,
     "lin"
    ],
    [
     1.18,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "01.18 \u884c\u3063\u3066\u307f\u305f\u3044\u3068\u601d\u3044\u307e\u3059",
   "t0": 1.18,
   "t1": 2.1,
   "lines": [
    {
     "size": 74,
     "runs": [
      {
       "text": "\u884c\u3063\u3066\u307f\u305f\u3044\u3068\u601d\u3044\u307e\u3059",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     1.18,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     1.18,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     1.18,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     1.18,
     0,
     "lin"
    ],
    [
     1.2466666666666666,
     100,
     "lin"
    ],
    [
     2.033333333333333,
     100,
     "lin"
    ],
    [
     2.1,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "02.38 \u65e5\u672c\u3060\u3068",
   "t0": 2.38,
   "t1": 2.84,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u65e5\u672c\u3060\u3068",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     2.38,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     2.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     2.38,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     2.38,
     0,
     "lin"
    ],
    [
     2.4466666666666668,
     100,
     "lin"
    ],
    [
     2.773333333333333,
     100,
     "lin"
    ],
    [
     2.84,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "02.84 \u30a4\u30b1\u30a2\u306e",
   "t0": 2.84,
   "t1": 3.16,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a4\u30b1\u30a2\u306e",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     2.84,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     2.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     2.84,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     2.84,
     0,
     "lin"
    ],
    [
     2.9066666666666667,
     100,
     "lin"
    ],
    [
     3.0933333333333333,
     100,
     "lin"
    ],
    [
     3.16,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "03.16 \u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
   "t0": 3.16,
   "t1": 3.7,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0\u3063\u3066",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     3.16,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     3.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     3.16,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     3.16,
     0,
     "lin"
    ],
    [
     3.226666666666667,
     100,
     "lin"
    ],
    [
     3.6333333333333333,
     100,
     "lin"
    ],
    [
     3.7,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "03.70 1\u500b50\u5186",
   "t0": 3.7,
   "t1": 4.38,
   "lines": [
    {
     "size": 190,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false
      },
      {
       "text": "50\u5186",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        3.7,
        218.49999999999997,
        "fast"
       ],
       [
        4.12,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     3.7,
     100,
     "lin"
    ],
    [
     4.38,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     3.7,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     3.7,
     [
      510,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     4.26,
     100,
     "io"
    ],
    [
     4.38,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     3.8800000000000003,
     0,
     "fast"
    ],
    [
     4.28,
     100,
     "lin"
    ]
   ]
  },
  {
   "name": "04.38 \u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
   "t0": 4.38,
   "t1": 5.2,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3060\u3068\u601d\u3046\u3093\u3067\u3059\u3051\u3069",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     4.38,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     4.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     4.38,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     4.38,
     0,
     "lin"
    ],
    [
     4.446666666666666,
     100,
     "lin"
    ],
    [
     5.133333333333334,
     100,
     "lin"
    ],
    [
     5.2,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "05.66 \u5b9f\u969b",
   "t0": 5.66,
   "t1": 6.02,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b9f\u969b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     5.66,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     5.66,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     5.66,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     5.66,
     0,
     "lin"
    ],
    [
     5.726666666666667,
     100,
     "lin"
    ],
    [
     5.953333333333333,
     100,
     "lin"
    ],
    [
     6.02,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "06.02 \u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
   "t0": 6.02,
   "t1": 7.22,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u672c\u5834\u306e\u30a4\u30b1\u30a2\u306f",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     6.02,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     6.02,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     6.02,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     6.02,
     0,
     "lin"
    ],
    [
     6.086666666666666,
     100,
     "lin"
    ],
    [
     7.153333333333333,
     100,
     "lin"
    ],
    [
     7.22,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "07.75 \u8cb7\u3048\u308b\u306e\u304b\u3092",
   "t0": 7.75,
   "t1": 8.04,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8cb7\u3048\u308b\u306e\u304b\u3092",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     7.75,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     7.75,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     7.75,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     7.75,
     0,
     "lin"
    ],
    [
     7.816666666666666,
     100,
     "lin"
    ],
    [
     7.973333333333333,
     100,
     "lin"
    ],
    [
     8.04,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "08.04 \u898b\u3066\u307f\u307e\u3059",
   "t0": 8.04,
   "t1": 8.8,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u898b\u3066\u307f\u307e\u3059",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     8.04,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     8.04,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     8.04,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     8.04,
     0,
     "lin"
    ],
    [
     8.106666666666666,
     100,
     "lin"
    ],
    [
     8.733333333333334,
     100,
     "lin"
    ],
    [
     8.8,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "08.98 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 8.98,
   "t1": 10.22,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     8.98,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     8.98,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     8.98,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     8.98,
     0,
     "lin"
    ],
    [
     9.046666666666667,
     100,
     "lin"
    ],
    [
     10.153333333333334,
     100,
     "lin"
    ],
    [
     10.22,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "10.22 9\u306a\u3093\u3067",
   "t0": 10.22,
   "t1": 11.74,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "9",
       "accent": true
      },
      {
       "text": "\u306a\u3093\u3067",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     10.22,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     10.22,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     10.22,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     10.22,
     0,
     "lin"
    ],
    [
     10.286666666666667,
     100,
     "lin"
    ],
    [
     11.673333333333334,
     100,
     "lin"
    ],
    [
     11.74,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "11.74 150\u5186",
   "t0": 11.74,
   "t1": 12.96,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "150\u5186",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        11.74,
        241.49999999999997,
        "fast"
       ],
       [
        12.16,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     11.74,
     100,
     "lin"
    ],
    [
     12.96,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     11.74,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     11.74,
     [
      510,
      950
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     12.840000000000002,
     100,
     "io"
    ],
    [
     12.96,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     11.92,
     0,
     "fast"
    ],
    [
     12.32,
     100,
     "lin"
    ]
   ]
  },
  {
   "name": "12.10 \u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
   "t0": 12.1,
   "t1": 12.96,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3050\u3089\u3044\u3067\u8cb7\u3048\u308b\u308f",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     12.1,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     12.1,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     12.1,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     12.1,
     0,
     "lin"
    ],
    [
     12.166666666666666,
     100,
     "lin"
    ],
    [
     12.893333333333334,
     100,
     "lin"
    ],
    [
     12.96,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "12.96 \u3053\u308c\u666e\u901a\u306b",
   "t0": 12.96,
   "t1": 13.74,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c\u666e\u901a\u306b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     12.96,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     12.96,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     12.96,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     12.96,
     0,
     "lin"
    ],
    [
     13.026666666666667,
     100,
     "lin"
    ],
    [
     13.673333333333334,
     100,
     "lin"
    ],
    [
     13.74,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "13.74 \u5b89\u3044\u3093\u3058\u3083\u306a\u3044\uff1f",
   "t0": 13.74,
   "t1": 14.38,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b89\u3044",
       "accent": true
      },
      {
       "text": "\u3093\u3058\u3083\u306a\u3044\uff1f",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     13.74,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     13.74,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     13.74,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     13.74,
     0,
     "lin"
    ],
    [
     13.806666666666667,
     100,
     "lin"
    ],
    [
     14.313333333333334,
     100,
     "lin"
    ],
    [
     14.38,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "14.38 \u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
   "t0": 14.38,
   "t1": 15.54,
   "lines": [
    {
     "size": 82,
     "runs": [
      {
       "text": "\u3053\u306e\u30b7\u30ca\u30e2\u30f3\u30ed\u30fc\u30eb\u306f",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     14.38,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     14.38,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     14.38,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     14.38,
     0,
     "lin"
    ],
    [
     14.446666666666667,
     100,
     "lin"
    ],
    [
     15.473333333333333,
     100,
     "lin"
    ],
    [
     15.54,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "15.54 1\u500b112\u5186",
   "t0": 15.54,
   "t1": 16.72,
   "lines": [
    {
     "size": 179,
     "runs": [
      {
       "text": "1\u500b",
       "accent": false
      },
      {
       "text": "112\u5186",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        15.54,
        205.85,
        "fast"
       ],
       [
        15.959999999999999,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     15.54,
     100,
     "lin"
    ],
    [
     16.72,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     15.54,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     15.54,
     [
      510,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     16.599999999999998,
     100,
     "io"
    ],
    [
     16.72,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     15.719999999999999,
     0,
     "fast"
    ],
    [
     16.119999999999997,
     100,
     "lin"
    ]
   ]
  },
  {
   "name": "16.72 \u3067\u8cb7\u3048\u307e\u3059\u306d",
   "t0": 16.72,
   "t1": 17.5,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3067\u8cb7\u3048\u307e\u3059\u306d",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     16.72,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     16.72,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     16.72,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     16.72,
     0,
     "lin"
    ],
    [
     16.786666666666665,
     100,
     "lin"
    ],
    [
     17.433333333333334,
     100,
     "lin"
    ],
    [
     17.5,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "17.76 \u30bb\u30c3\u30c8\u3057\u3066",
   "t0": 17.76,
   "t1": 18.8,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30bb\u30c3\u30c8\u3057\u3066",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     17.76,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     17.76,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     17.76,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     17.76,
     0,
     "lin"
    ],
    [
     17.826666666666668,
     100,
     "lin"
    ],
    [
     18.733333333333334,
     100,
     "lin"
    ],
    [
     18.8,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "19.16 \u3042\u3068\u306f\u3053\u3053\u3092",
   "t0": 19.16,
   "t1": 20.08,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u3068\u306f\u3053\u3053\u3092",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     19.16,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     19.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     19.16,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     19.16,
     0,
     "lin"
    ],
    [
     19.226666666666667,
     100,
     "lin"
    ],
    [
     20.013333333333332,
     100,
     "lin"
    ],
    [
     20.08,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "20.08 \u62bc\u3059\u3060\u3051\u3067\u3059\u306d",
   "t0": 20.08,
   "t1": 21.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u62bc\u3059\u3060\u3051",
       "accent": true
      },
      {
       "text": "\u3067\u3059\u306d",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     20.08,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     20.08,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     20.08,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     20.08,
     0,
     "lin"
    ],
    [
     20.146666666666665,
     100,
     "lin"
    ],
    [
     20.933333333333334,
     100,
     "lin"
    ],
    [
     21.0,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "23.04 \u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
   "t0": 23.04,
   "t1": 24.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u81ea\u52d5\u3067\u3084\u3063\u3066\u304f\u308c\u308b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     23.04,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     23.04,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     23.04,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     23.04,
     0,
     "lin"
    ],
    [
     23.106666666666666,
     100,
     "lin"
    ],
    [
     23.933333333333334,
     100,
     "lin"
    ],
    [
     24.0,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "24.84 \u5b9f\u969b\u306b",
   "t0": 24.84,
   "t1": 26.04,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u5b9f\u969b\u306b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     24.84,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     24.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     24.84,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     24.84,
     0,
     "lin"
    ],
    [
     24.906666666666666,
     100,
     "lin"
    ],
    [
     25.973333333333333,
     100,
     "lin"
    ],
    [
     26.04,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "26.04 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0 \u98df\u3079\u307e\u3059",
   "t0": 26.04,
   "t1": 26.95,
   "lines": [
    {
     "size": 90,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ],
     "keys": {
      "dy": [
       [
        26.04,
        103.49999999999999,
        "fast"
       ],
       [
        26.46,
        0,
        "lin"
       ]
      ]
     }
    },
    {
     "size": 190,
     "runs": [
      {
       "text": "\u98df\u3079\u307e\u3059",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        26.119999999999997,
        218.49999999999997,
        "fast"
       ],
       [
        26.54,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     26.04,
     100,
     "lin"
    ],
    [
     26.95,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     26.04,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     26.04,
     [
      510,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     26.83,
     100,
     "io"
    ],
    [
     26.95,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "29.48 \u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
   "t0": 29.48,
   "t1": 30.48,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u53e3\u306e\u4e2d\u306b\u5165\u308c\u305f",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     29.48,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     29.48,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     29.48,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     29.48,
     0,
     "lin"
    ],
    [
     29.546666666666667,
     100,
     "lin"
    ],
    [
     30.413333333333334,
     100,
     "lin"
    ],
    [
     30.48,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "30.48 \u77ac\u9593\u306b",
   "t0": 30.48,
   "t1": 31.3,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u77ac\u9593\u306b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     30.48,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     30.48,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     30.48,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     30.48,
     0,
     "lin"
    ],
    [
     30.546666666666667,
     100,
     "lin"
    ],
    [
     31.233333333333334,
     100,
     "lin"
    ],
    [
     31.3,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "31.90 \u3046\u308f\u3063\uff01\u3063\u3066",
   "t0": 31.9,
   "t1": 32.78,
   "lines": [
    {
     "size": 137,
     "runs": [
      {
       "text": "\u3046\u308f\u3063\uff01",
       "accent": true
      },
      {
       "text": "\u3063\u3066",
       "accent": false
      }
     ],
     "keys": {
      "dy": [
       [
        31.9,
        157.54999999999998,
        "fast"
       ],
       [
        32.32,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     31.9,
     100,
     "lin"
    ],
    [
     32.78,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     31.9,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     31.9,
     [
      510,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     32.660000000000004,
     100,
     "io"
    ],
    [
     32.78,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "32.78 \u8272\u3005\u3046\u307e\u3044",
   "t0": 32.78,
   "t1": 33.68,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u8272\u3005\u3046\u307e\u3044",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     32.78,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     32.78,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     32.78,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     32.78,
     0,
     "lin"
    ],
    [
     32.84666666666667,
     100,
     "lin"
    ],
    [
     33.61333333333333,
     100,
     "lin"
    ],
    [
     33.68,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "33.68 \u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
   "t0": 33.68,
   "t1": 34.16,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u30a2\u30a4\u30b9\u30af\u30ea\u30fc\u30e0",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     33.68,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     33.68,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     33.68,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     33.68,
     0,
     "lin"
    ],
    [
     33.74666666666667,
     100,
     "lin"
    ],
    [
     34.09333333333333,
     100,
     "lin"
    ],
    [
     34.16,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "34.16 \u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
   "t0": 34.16,
   "t1": 35.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3042\u308b\u3058\u3083\u306a\u3044\u3067\u3059\u304b",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     34.16,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     34.16,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     34.16,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     34.16,
     0,
     "lin"
    ],
    [
     34.22666666666667,
     100,
     "lin"
    ],
    [
     34.93333333333333,
     100,
     "lin"
    ],
    [
     35.0,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "35.14 \u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
   "t0": 35.14,
   "t1": 36.18,
   "lines": [
    {
     "size": 82,
     "runs": [
      {
       "text": "\u307e\u3042\u30cf\u30fc\u30b2\u30f3\u30c0\u30c3\u30c4\u306e",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     35.14,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     35.14,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     35.14,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     35.14,
     0,
     "lin"
    ],
    [
     35.20666666666667,
     100,
     "lin"
    ],
    [
     36.11333333333333,
     100,
     "lin"
    ],
    [
     36.18,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "36.18 5\u500d\u6fc3\u7e2e",
   "t0": 36.18,
   "t1": 37.4,
   "lines": [
    {
     "size": 210,
     "runs": [
      {
       "text": "5\u500d\u6fc3\u7e2e",
       "accent": true
      }
     ],
     "keys": {
      "dy": [
       [
        36.18,
        241.49999999999997,
        "fast"
       ],
       [
        36.6,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": true,
   "scale": [
    [
     36.18,
     100,
     "lin"
    ],
    [
     37.4,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     36.18,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     36.18,
     [
      510,
      400
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     37.28,
     100,
     "io"
    ],
    [
     37.4,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "36.84 \u3057\u305f\u307f\u305f\u3044\u306a",
   "t0": 36.84,
   "t1": 37.28,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3057\u305f\u307f\u305f\u3044\u306a",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     36.84,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     36.84,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     36.84,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     36.84,
     0,
     "lin"
    ],
    [
     36.90666666666667,
     100,
     "lin"
    ],
    [
     37.21333333333333,
     100,
     "lin"
    ],
    [
     37.28,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "37.28 \u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
   "t0": 37.28,
   "t1": 38.0,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u611f\u3058\u306e\u5473\u304c\u3057\u307e\u3059",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     37.28,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     37.28,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     37.28,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     37.28,
     0,
     "lin"
    ],
    [
     37.34666666666667,
     100,
     "lin"
    ],
    [
     37.93333333333333,
     100,
     "lin"
    ],
    [
     38.0,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "38.00 \u3053\u308c",
   "t0": 38.0,
   "t1": 38.6,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u3053\u308c",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     38.0,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     38.0,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     38.0,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     38.0,
     0,
     "lin"
    ],
    [
     38.06666666666667,
     100,
     "lin"
    ],
    [
     38.53333333333333,
     100,
     "lin"
    ],
    [
     38.6,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "39.24 \u610f\u5916\u3068\u306d",
   "t0": 39.24,
   "t1": 39.68,
   "lines": [
    {
     "size": 84,
     "runs": [
      {
       "text": "\u610f\u5916\u3068\u306d",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     39.24,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     39.24,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     39.24,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     39.24,
     0,
     "lin"
    ],
    [
     39.30666666666667,
     100,
     "lin"
    ],
    [
     39.61333333333333,
     100,
     "lin"
    ],
    [
     39.68,
     0,
     "lin"
    ]
   ],
   "bar": null
  },
  {
   "name": "39.68 \u30ea\u30fc\u30ba\u30ca\u30d6\u30eb\u306a\u306e\u3067",
   "t0": 39.68,
   "t1": 40.42,
   "lines": [
    {
     "size": 91,
     "runs": [
      {
       "text": "\u30ea\u30fc\u30ba\u30ca\u30d6\u30eb",
       "accent": true
      },
      {
       "text": "\u306a\u306e\u3067",
       "accent": false
      }
     ],
     "keys": {
      "dy": [
       [
        39.68,
        104.64999999999999,
        "fast"
       ],
       [
        40.1,
        0,
        "lin"
       ]
      ]
     }
    }
   ],
   "anim": "mask",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     39.68,
     100,
     "lin"
    ],
    [
     40.42,
     103.0,
     "lin"
    ]
   ],
   "rot": [
    [
     39.68,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     39.68,
     [
      510,
      985
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     40.300000000000004,
     100,
     "io"
    ],
    [
     40.42,
     0,
     "lin"
    ]
   ],
   "bar": [
    [
     39.86,
     0,
     "fast"
    ],
    [
     40.26,
     100,
     "lin"
    ]
   ]
  },
  {
   "name": "40.42 \u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
   "t0": 40.42,
   "t1": 42.3,
   "lines": [
    {
     "size": 74,
     "runs": [
      {
       "text": "\u305c\u3072\u98df\u3079\u3066\u307f\u3066\u304f\u3060\u3055\u3044",
       "accent": false
      }
     ],
     "keys": {}
    }
   ],
   "anim": "static",
   "font": "RoundedMplus1c-Black",
   "color": [
    1.0,
    1.0,
    1.0
   ],
   "accent": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "border": true,
   "behind": false,
   "scale": [
    [
     40.42,
     100,
     "lin"
    ]
   ],
   "rot": [
    [
     40.42,
     0.0,
     "lin"
    ]
   ],
   "pos": [
    [
     40.42,
     [
      510,
      1150
     ],
     "lin"
    ]
   ],
   "opacity": [
    [
     40.42,
     0,
     "lin"
    ],
    [
     40.48666666666667,
     100,
     "lin"
    ],
    [
     42.23333333333333,
     100,
     "lin"
    ],
    [
     42.3,
     0,
     "lin"
    ]
   ],
   "bar": null
  }
 ],
 "cards": [
  {
   "t0": 7.22,
   "t1": 7.75,
   "bg": [
    1.0,
    0.8235294117647058,
    0.12156862745098039
   ],
   "telop": {
    "name": "07.22 \u3044\u304f\u3089\uff1f",
    "t0": 7.22,
    "t1": 7.75,
    "lines": [
     {
      "size": 206,
      "runs": [
       {
        "text": "\u3044\u304f\u3089\uff1f",
        "accent": false
       }
      ],
      "keys": {
       "dy": [
        [
         7.22,
         236.89999999999998,
         "fast"
        ],
        [
         7.64,
         0,
         "lin"
        ]
       ]
      }
     }
    ],
    "anim": "mask",
    "font": "RoundedMplus1c-Black",
    "color": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "accent": [
     0.11764705882352941,
     0.10980392156862745,
     0.10196078431372549
    ],
    "border": false,
    "behind": false,
    "scale": [
     [
      7.22,
      100,
      "lin"
     ],
     [
      7.75,
      103.0,
      "lin"
     ]
    ],
    "rot": [
     [
      7.22,
      0.0,
      "lin"
     ]
    ],
    "pos": [
     [
      7.22,
      [
       510,
       760
      ],
      "lin"
     ]
    ],
    "opacity": [
     [
      7.63,
      100,
      "io"
     ],
     [
      7.75,
      0,
      "lin"
     ]
    ],
    "bar": null
   }
  }
 ],
 "behindSegments": [
  [
   36.18,
   37.4
  ]
 ],
 "safe": {
  "left": 60,
  "top": 250,
  "right": 960,
  "bottom": 1250
 },
 "tracking": -30,
 "border": 0.022,
 "lineGap": 0.12,
 "barH": 0.07,
 "dark": [
  0.11764705882352941,
  0.10980392156862745,
  0.10196078431372549
 ],
 "yellow": [
  1.0,
  0.8235294117647058,
  0.12156862745098039
 ],
 "hookEnd": 2.1,
 "hookDim": [
  [
   0,
   40.0,
   "lin"
  ],
  [
   1.85,
   40.0,
   "io"
  ],
  [
   2.1,
   0,
   "lin"
  ]
 ]
};
var MSG = {"intro": "IKEA\u30bd\u30d5\u30c8\u30af\u30ea\u30fc\u30e0 \u7de8\u96c6\u30d7\u30ed\u30b8\u30a7\u30af\u30c8\u3092\u4f5c\u308a\u307e\u3059\u3002\n\u5148\u306b fonts \u30d5\u30a9\u30eb\u30c0\u306e\u30d5\u30a9\u30f3\u30c8\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u304a\u3044\u3066\u304f\u3060\u3055\u3044\u3002\n\u6b21\u306e\u753b\u9762\u3067\u7d20\u6750\u52d5\u753b\uff08\u7de8\u96c6\u524d\u306e\u9ad8\u753b\u8cea\u7248\uff09\u3092\u9078\u3093\u3067\u304f\u3060\u3055\u3044\u3002", "pick": "\u7d20\u6750\u52d5\u753b\u3092\u9078\u629e", "done": "\u5b8c\u6210\u3057\u307e\u3057\u305f\u3002\u8d64\u3044\u90e8\u5206\u306f\u30ea\u30fc\u30eb\u306eUI\u3067\u96a0\u308c\u308b\u7bc4\u56f2\u3067\u3059\uff08\u30ac\u30a4\u30c9\u30ec\u30a4\u30e4\u30fc\u306a\u306e\u3067\u66f8\u304d\u51fa\u3057\u306b\u306f\u5165\u308a\u307e\u305b\u3093\uff09\u3002"};
var W = 1080, H = 1920, FPS = 30;
var root = File($.fileName).parent;
var WARN = [];

function xf(L) { return L.property("ADBE Transform Group"); }
function setMax(prop, frac) { prop.setValue(prop.hasMax ? prop.maxValue * frac : frac * 100); }
function dims(prop) { var v = prop.value; return (v instanceof Array && !prop.isSpatial) ? v.length : 1; }
function easeArr(n, inf) { var a = []; for (var i = 0; i < n; i++) a.push(new KeyframeEase(0, inf)); return a; }

// keys: [[time, value, ease]]; ease of a key describes the segment that leaves it:
// "lin" linear, "fast" expo-like ease-out, "io" ease in-out.  conv(value) -> AE value.
function applyKeys(prop, keys, conv) {
    var i, n = dims(prop);
    for (i = 0; i < keys.length; i++) prop.setValueAtTime(keys[i][0], conv ? conv(keys[i][1]) : keys[i][1]);
    if (keys.length < 2) return;
    for (i = 1; i <= prop.numKeys; i++) {
        var outE = i <= keys.length ? keys[i - 1][2] : "lin";
        var inE = i > 1 ? keys[i - 2][2] : "lin";
        var linIn = inE === "lin", linOut = outE === "lin";
        var inInf = inE === "fast" ? 92 : 50, outInf = outE === "fast" ? 0.1 : 50;
        if (!linIn || !linOut) prop.setTemporalEaseAtKey(i, easeArr(n, linIn ? 33 : inInf), easeArr(n, linOut ? 33 : outInf));
        prop.setInterpolationTypeAtKey(i,
            linIn ? KeyframeInterpolationType.LINEAR : KeyframeInterpolationType.BEZIER,
            linOut ? KeyframeInterpolationType.LINEAR : KeyframeInterpolationType.BEZIER);
    }
    if (prop.isSpatial) for (i = 1; i <= prop.numKeys; i++) { try { prop.setSpatialAutoBezierAtKey(i, false); } catch (e) {} }
}
function sc3(v) { return [v, v, 100]; }
function dy3(v) { return [0, v, 0]; }

function addShadow(L, size) {
    var ds = L.property("ADBE Effect Parade").addProperty("ADBE Drop Shadow");
    ds.property("ADBE Drop Shadow-0001").setValue([0, 0, 0, 1]);
    setMax(ds.property("ADBE Drop Shadow-0002"), 0.55);
    ds.property("ADBE Drop Shadow-0003").setValue(180);
    ds.property("ADBE Drop Shadow-0004").setValue(Math.max(2, size * 0.03));
    ds.property("ADBE Drop Shadow-0005").setValue(Math.max(4, size * 0.12));
}

function addRun(comp, text, size, color, border, fontName) {
    var L = comp.layers.addText(text);
    var src = L.property("ADBE Text Properties").property("ADBE Text Document");
    var td = src.value;
    try { td.resetCharStyle(); td.resetParagraphStyle(); } catch (e) {}
    td.font = fontName; td.fontSize = size; td.tracking = DATA.tracking;
    td.applyFill = true; td.fillColor = color;
    if (border) {  // thin dark border drawn behind the fill
        td.applyStroke = true; td.strokeColor = DATA.dark; td.strokeOverFill = false;
        td.strokeWidth = Math.max(2, Math.round(size * DATA.border * 2));
    } else td.applyStroke = false;
    td.justification = ParagraphJustification.LEFT_JUSTIFY;
    src.setValue(td);
    if (border) addShadow(L, size);
    return L;
}

function animators(L) { return L.property("ADBE Text Properties").property("ADBE Text Animators"); }
function addAnimator(L, name, props) {
    animators(L).addProperty("ADBE Text Animator");
    var ai = animators(L).numProperties;
    animators(L).property(ai).name = name;
    for (var i = 0; i < props.length; i++)
        animators(L).property(ai).property("ADBE Text Animator Properties").addProperty(props[i]);
    return function (n) { return animators(L).property(ai).property("ADBE Text Animator Properties").property(n); };
}

// mask: the run rises from behind the lower edge of a layer mask (the mask does not move with the animator)
function addMaskRise(L, rect, size, keys) {
    var m = L.property("ADBE Mask Parade").addProperty("ADBE Mask Atom");
    var s = new Shape(), padX = size * 0.3, top = rect.top - size * 0.3, bot = rect.top + rect.height + size * 0.08;
    s.vertices = [[rect.left - padX, top], [rect.left + rect.width + padX, top],
                  [rect.left + rect.width + padX, bot], [rect.left - padX, bot]];
    s.closed = true;
    m.property("ADBE Mask Shape").setValue(s);
    var pr = addAnimator(L, "Rise", ["ADBE Text Position 3D"]);
    applyKeys(pr("ADBE Text Position 3D"), keys.dy, dy3);
}

// track: letter spacing collapses while fading in
function addTrackIn(L, keys) {
    var pr = addAnimator(L, "Track in", ["ADBE Text Tracking Amount", "ADBE Text Opacity"]);
    applyKeys(pr("ADBE Text Tracking Amount"), keys.tracking);
    applyKeys(pr("ADBE Text Opacity"), keys.opacity);
}

function addBar(comp, nul, x, y, w, size, keys, t0, t1) {
    var L = comp.layers.addShape();
    var root = L.property("ADBE Root Vectors Group");
    root.addProperty("ADBE Vector Group");
    var g = function () { return root.property(1).property("ADBE Vectors Group"); };
    g().addProperty("ADBE Vector Shape - Rect"); g().addProperty("ADBE Vector Graphic - Fill");
    var h = Math.max(3, Math.round(size * DATA.barH));
    g().property(1).property("ADBE Vector Rect Size").setValue([w, h]);
    g().property(1).property("ADBE Vector Rect Position").setValue([w / 2, h / 2]);
    g().property(2).property("ADBE Vector Fill Color").setValue(DATA.yellow);
    L.parent = nul;
    xf(L).property("ADBE Anchor Point").setValue([0, 0]);
    xf(L).property("ADBE Position").setValue([x, y]);
    applyKeys(xf(L).property("ADBE Scale"), keys, function (v) { return [v, 100, 100]; });
    L.inPoint = t0; L.outPoint = t1;
    return L;
}

// One telop = a null (position / slow push-in) + one text layer per colour run.
function addPhrase(comp, p) {
    var nul = comp.layers.addNull(comp.duration);
    nul.name = "TELOP " + p.name;
    nul.startTime = 0; nul.inPoint = p.t0; nul.outPoint = p.t1;
    xf(nul).property("ADBE Anchor Point").setValue([0, 0, 0]);
    applyKeys(xf(nul).property("ADBE Position"), p.pos);
    applyKeys(xf(nul).property("ADBE Scale"), p.scale, sc3);
    applyKeys(xf(nul).property("ADBE Rotate Z"), p.rot);
    var lineBoxes = [], totalH = 0, li, k;
    for (li = 0; li < p.lines.length; li++) {
        var line = p.lines[li], lw = 0, top = 1e9, bot = -1e9, items = [];
        for (var ri = 0; ri < line.runs.length; ri++) {
            var run = line.runs[ri];
            var L = addRun(comp, run.text, line.size, run.accent ? p.accent : p.color, p.border, p.font);
            L.startTime = 0; L.inPoint = p.t0; L.outPoint = p.t1;
            var r = L.sourceRectAtTime(p.t1 - 0.01, false);
            items.push({ layer: L, rect: r, x: lw });
            lw += r.width + line.size * DATA.tracking / 1000;
            top = Math.min(top, r.top); bot = Math.max(bot, r.top + r.height);
        }
        lineBoxes.push({ items: items, width: lw - line.size * DATA.tracking / 1000, top: top, bot: bot,
                         size: line.size, keys: line.keys });
        totalH += (bot - top) + (li ? line.size * DATA.lineGap : 0);
    }
    var y = -totalH / 2;
    for (li = 0; li < lineBoxes.length; li++) {
        var lb = lineBoxes[li];
        if (li) y += lb.size * DATA.lineGap;
        for (k = 0; k < lb.items.length; k++) {
            var it = lb.items[k];
            it.layer.parent = nul;
            xf(it.layer).property("ADBE Position").setValue([-lb.width / 2 + it.x - it.rect.left, y - lb.top]);
            it.layer.name = "  " + p.name + " / " + (li + 1) + "-" + (k + 1);
            applyKeys(xf(it.layer).property("ADBE Opacity"), p.opacity);
            try {
                if (p.anim === "mask") addMaskRise(it.layer, it.rect, lb.size, lb.keys);
                else if (p.anim === "track") addTrackIn(it.layer, lb.keys);
            } catch (e) { WARN.push(p.name + ": " + e.toString()); }
        }
        y += lb.bot - lb.top;
        if (p.bar && li === lineBoxes.length - 1) {
            try {
                var bar = addBar(comp, nul, -lb.width / 2, y + lb.size * 0.08, lb.width, lb.size, p.bar, p.t0, p.t1);
                bar.name = "  " + p.name + " / underline";
                applyKeys(xf(bar).property("ADBE Opacity"), p.opacity);
            } catch (e2) { WARN.push(p.name + " underline: " + e2.toString()); }
        }
    }
    return nul;
}

// ---------- shape helpers
function shapeLayer(comp, name) {
    var L = comp.layers.addShape(); L.name = name;
    xf(L).property("ADBE Position").setValue([0, 0]);
    return L;
}
function addRect(L, cx, cy, w, h, color, opacity) {
    var root = L.property("ADBE Root Vectors Group");
    root.addProperty("ADBE Vector Group");
    var gi = root.numProperties;
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Shape - Rect");
    root.property(gi).property("ADBE Vectors Group").addProperty("ADBE Vector Graphic - Fill");
    var c = root.property(gi).property("ADBE Vectors Group");
    c.property(1).property("ADBE Vector Rect Size").setValue([w, h]);
    c.property(2).property("ADBE Vector Fill Color").setValue(color);
    c.property(2).property("ADBE Vector Fill Opacity").setValue(opacity);
    root.property(gi).property("ADBE Vector Transform Group").property("ADBE Vector Position").setValue([cx, cy]);
}

function addCard(comp, c, idx) {
    var solid = comp.layers.addSolid(c.bg, "CARD " + idx + " bg", W, H, 1, comp.duration);
    solid.inPoint = c.t0; solid.outPoint = c.t1;
    var st = shapeLayer(comp, "CARD " + idx + " light");
    for (var k = -6; k <= 6; k++) addRect(st, 540, 960 + k * 320, 3200, 140, k % 2 ? [1, 1, 1] : [0, 0, 0], 7);
    xf(st).property("ADBE Anchor Point").setValue([540, 960]);
    xf(st).property("ADBE Rotate Z").setValue(-30);
    xf(st).property("ADBE Position").setValuesAtTimes([c.t0, c.t1], [[540, 960], [590, 990]]);
    st.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2").property("ADBE Gaussian Blur 2-0001").setValue(90);
    st.inPoint = c.t0; st.outPoint = c.t1;
    addPhrase(comp, c.telop);
}

function addSafeGuide(comp) {
    var g = shapeLayer(comp, "GUIDE  Reels safe zone (not rendered)");
    var s = DATA.safe, red = [1, 0.15, 0.15];
    addRect(g, W / 2, s.top / 2, W, s.top, red, 25);
    addRect(g, W / 2, (s.bottom + H) / 2, W, H - s.bottom, red, 25);
    addRect(g, s.left / 2, (s.top + s.bottom) / 2, s.left, s.bottom - s.top, red, 25);
    addRect(g, (s.right + W) / 2, (s.top + s.bottom) / 2, W - s.right, s.bottom - s.top, red, 25);
    g.guideLayer = true;
}

function importFile(path) {
    var f = new File(path);
    if (!f.exists) return null;
    return app.project.importFile(new ImportOptions(f));
}

// ---------------------------------------------------------- build
app.beginUndoGroup("IKEA soft-ice edit");
try {
    if (!app.project) app.newProject();
    alert(MSG.intro);
    var srcFile = File.openDialog(MSG.pick);
    var folder = app.project.items.addFolder("IKEA_edit");
    var comp = app.project.items.addComp("IKEA_SoftCream_Reel", W, H, 1, DATA.duration, FPS);
    comp.parentFolder = folder;
    comp.motionBlur = true;
    comp.bgColor = [0, 0, 0];

    var srcItem = srcFile ? app.project.importFile(new ImportOptions(srcFile)) : null;
    if (srcItem) srcItem.parentFolder = folder;
    function addFootage(name) {
        var L = srcItem ? comp.layers.add(srcItem) : comp.layers.addSolid([0.5, 0.5, 0.5], "REPLACE ME footage", W, H, 1, DATA.duration);
        L.name = name;
        if (srcItem && srcItem.width) {
            var s = Math.max(W / srcItem.width, H / srcItem.height) * 100;
            xf(L).property("ADBE Scale").setValue([s, s, 100]);
        }
        return L;
    }
    addFootage("FOOTAGE (base)");

    // darken the opening shot so the hook reads
    var dim = comp.layers.addSolid([0, 0, 0], "HOOK dim", W, H, 1, comp.duration);
    dim.inPoint = 0; dim.outPoint = DATA.hookEnd;
    applyKeys(xf(dim).property("ADBE Opacity"), DATA.hookDim);

    var i;
    for (i = 0; i < DATA.telops.length; i++) if (DATA.telops[i].behind) addPhrase(comp, DATA.telops[i]);

    var matteItem = importFile(root.fsName + "/matte/person_matte.mp4");
    if (matteItem) matteItem.parentFolder = folder;
    for (var sgi = 0; sgi < DATA.behindSegments.length; sgi++) {
        var seg = DATA.behindSegments[sgi];
        var cut = addFootage("PERSON cut-out " + (sgi + 1));
        if (srcItem) cut.audioEnabled = false;
        cut.inPoint = seg[0]; cut.outPoint = seg[1];
        if (matteItem) {
            var mt = comp.layers.add(matteItem);
            mt.name = "PERSON matte " + (sgi + 1) + " (luma)";
            mt.inPoint = seg[0]; mt.outPoint = seg[1];
            if (mt.hasAudio) mt.audioEnabled = false;
            if (typeof cut.setTrackMatte === "function") { cut.setTrackMatte(mt, TrackMatteType.LUMA); mt.enabled = false; }
            else { mt.moveBefore(cut); cut.trackMatteType = TrackMatteType.LUMA; }
        }
    }

    for (i = 0; i < DATA.telops.length; i++) if (!DATA.telops[i].behind) addPhrase(comp, DATA.telops[i]);
    for (i = 0; i < DATA.cards.length; i++) addCard(comp, DATA.cards[i], i + 1);

    var sfx = importFile(root.fsName + "/sfx/sfx_mix.wav");
    if (sfx) { sfx.parentFolder = folder; var sl = comp.layers.add(sfx); sl.name = "SFX mix"; }

    addSafeGuide(comp);
    comp.openInViewer();
    alert(MSG.done + (WARN.length ? "\n\n" + WARN.slice(0, 8).join("\n") : ""));
} catch (err) {
    alert("Error: " + err.toString() + " (line " + err.line + ")");
}
app.endUndoGroup();
})();
